export interface Video {
  id: string
  title: string
}

export interface Category {
  id: string
  name: string
  description: string
  videoCount: number
  icon: string
  gradient: string
  featuredVideos: Video[]
}

export interface NinjaConcept {
  id: string
  name: string
  description: string
  principles: string[]
  actionItems: string[]
}

export const categories: Category[] = [
  { id: "personal-mastery-and-mindset", name: "Personal Mastery & Mindset", description: "Developing a growth mindset, personal mastery, self-improvement, confidence, abundance vs. scarcity thinking, energy management, overcoming fear and limiting beliefs, and the mental game of success.", videoCount: 134, icon: "Brain", gradient: "from-purple-500 to-indigo-600", featuredVideos: [{ id: "IS1470U8xiM", title: "What is Personal Mastery in Ninja Selling?" }, { id: "LtF7nlt2lYk", title: "The Level Up Moment: Leading with Mindset, Skillset, and Action" }, { id: "VFJZeD6iWU8", title: "Building Unshakable Confidence for Real Estate Agents" }, { id: "CRWe1eirLYU", title: "The Perception of Power, Party, Peace, and Perfection Personality Profiles" }, { id: "4lwMtg1zP18", title: "Personal Mastery: The First Cornerstone of Ninja" }] },
  { id: "ninja-selling-system-foundations", name: "Ninja Selling System Foundations", description: "Core introductions to the Ninja Selling system, its philosophy, the four cornerstones, installations, rules, foundational concepts, and the Ninja path.", videoCount: 40, icon: "BookOpen", gradient: "from-teal-500 to-cyan-600", featuredVideos: [{ id: "2WKDpsTEOTY", title: "Ninja In A Nutshell - An Overview of the Ninja Selling System" }, { id: "WC_nezGrWJ4", title: "Live From The Ninja Installation: Trust the Process" }, { id: "LCel0MB8Bw0", title: "Stop Selling. Start Solving. The Second Cornerstone" }, { id: "HXf2015FQF8", title: "Rule #3: Do what you say and keep your commitments" }, { id: "HtLnbYcSsA0", title: "Rule #5: Don't get attached to the outcome" }] },
  { id: "business-planning-and-goal-setting", name: "Business Planning & Goal Setting", description: "Annual and quarterly business planning, goal setting, financial targets, life lists, word of the year, and strategic planning frameworks for building a successful real estate career.", videoCount: 35, icon: "Target", gradient: "from-emerald-500 to-green-600", featuredVideos: [{ id: "py6pKEst_Hc", title: "Ninja Business Plan Step One: Build your Life List" }, { id: "3W_QeKRoi8w", title: "Understanding Your Business Model to Determine Next Steps" }, { id: "-QLdV8uPtZE", title: "How to Finish Strong and Set Up for Success" }, { id: "tp3-f7IfZNI", title: "Finish Strong by Reviewing What Worked (and What Didn't)" }, { id: "2bfFs1n5kZ0", title: "10 Step Formula to a Successful Year" }] },
  { id: "ninja-nine-and-daily-habits", name: "Ninja Nine & Daily Habits", description: "The nine daily and weekly habits that form the foundation of the Ninja Selling system, including gratitude, affirmations, morning routines, scorecards, the Ninja Planner, time blocking, and tracking progress.", videoCount: 32, icon: "ListChecks", gradient: "from-blue-500 to-indigo-600", featuredVideos: [{ id: "FGOcbj_n-EU", title: "Best of Weekly Action Tips: Excellence is a Habit" }, { id: "fHjA3deWjS4", title: "Best of Weekly Action Tips: Never Break the Chain" }, { id: "1lxD6ibUcG0", title: "Mastering the Ninja Planner with Creator Eric Hardy" }, { id: "UedLGJTp9KU", title: "Want More Closings? Master Your PIE Time" }, { id: "JAgIsaRpZ5c", title: "The Ninja Scorecard - Your Plan for Consistency" }] },
  { id: "market-updates-and-economic-insights", name: "Market Updates & Economic Insights", description: "Analysis of current real estate market conditions, interest rates, housing trends, economic indicators, mortgage insights, inventory levels, and navigating market shifts.", videoCount: 29, icon: "TrendingUp", gradient: "from-orange-500 to-red-600", featuredVideos: [{ id: "MO_CPEilpfw", title: "Consistent Volume in an Inconsistent Market Using Consistent Routines" }, { id: "SQplLwWwh7k", title: "What is going on with values in their neighborhood?" }, { id: "qKRDyrp5aoc", title: "Insights and Opportunities in Today's Real Estate Market" }, { id: "APK1mycdSM0", title: "This Economic Indicator Could Be Your Next Opportunity" }, { id: "iRBxDL_r10s", title: "Understanding and Outperforming the Market" }] },
  { id: "general-ninja-wisdom-and-motivation", name: "General Ninja Wisdom & Motivation", description: "Broader motivational content, general business wisdom, seasonal messages, and miscellaneous tips that reinforce the Ninja mindset and approach to business and life.", videoCount: 29, icon: "Sparkles", gradient: "from-yellow-500 to-orange-600", featuredVideos: [{ id: "D5A55uPxzTY", title: "The Opportunities in Change - Larry Kendall, Jack Miller, Mike Staver" }, { id: "u5YVRqJBRKg", title: "Navigating False Flats to Keep Your Business Booming" }, { id: "5Pi1-Ke9ymQ", title: "Plan Before There is Demand" }, { id: "Wo4NXpO17Ok", title: "Navigating a Reactionary Society" }, { id: "YmqayfSZK0Q", title: "The Stuff Trap" }] },
  { id: "flow-and-auto-flow-systems", name: "Flow & Auto-Flow Systems", description: "Ninja Selling's systematic approach to staying in touch with your database through automated and intentional touchpoints, customer service calls, flow schedules, and systematic follow-up.", videoCount: 22, icon: "Repeat", gradient: "from-cyan-500 to-blue-600", featuredVideos: [{ id: "r1QbMt3Xjto", title: "Auto-Flow 101: Why Flow Fixes Everything" }, { id: "NYIhCLe-ZFo", title: "Why 'Flow Fixes Everything' in Real Estate" }, { id: "fge6q4Qbgj8", title: "Frictionless Referrals: Introducing Referral Flow" }, { id: "9IrI5eCIGNg", title: "The Secret to Guilt-Free Client Follow Up" }, { id: "n-_1Xu5ZUpY", title: "Rebuilding on Purpose Through Flow" }] },
  { id: "referrals-and-relationship-building", name: "Referrals & Relationship Building", description: "Building a referral-based business through genuine relationships, becoming referable, creating raving fans, and generating business through authentic connection rather than hard selling.", videoCount: 21, icon: "Heart", gradient: "from-rose-500 to-pink-600", featuredVideos: [{ id: "WxPQzM6iqTU", title: "How To Generate Referrals Without Asking" }, { id: "yu_7yzbLHfU", title: "How To Be Consistently Magnetic" }, { id: "wITbrOHEWAg", title: "The Power of Creating Raving Fans" }, { id: "49PhQ8nwzjM", title: "This Simple Action Creates Referrals (and it's Not Selling)" }, { id: "me6shlzYhb8", title: "Relationships, Service, and Building Social Proof" }] },
  { id: "ninja-coaching-spotlights", name: "Ninja Coaching Spotlights", description: "Spotlight interviews with Ninja coaches sharing insights, strategies, and coaching success stories that illustrate how Ninja principles work in real-world coaching scenarios.", videoCount: 18, icon: "Mic", gradient: "from-indigo-500 to-purple-600", featuredVideos: [{ id: "TUSgP6pL-Ho", title: "Ninja Coaches: Why Agents Use Them To Win" }, { id: "ftqxEQvV0M0", title: "Coaching Spotlight with Christine Moore and Tracy Peterson-Nienaber" }, { id: "-GvT0jBhB8c", title: "Coaching Spotlight with Patty Schmitz-Thursam and Natalie Davis" }, { id: "8-B8RO455ME", title: "Coaching Spotlight on Peggy Shanklin and Shelly Culbertson" }, { id: "NTsUTd6p0Ok", title: "Coaching Spotlight with Christina O'Neal and Mark Johnson" }] },
  { id: "time-management-and-productivity", name: "Time Management & Productivity", description: "Time blocking, calendar management, productivity strategies, work-life harmony, the PIE framework (Proactive, Income, Education time), and creating efficient daily routines.", videoCount: 17, icon: "Clock", gradient: "from-emerald-500 to-teal-600", featuredVideos: [{ id: "gyTv6IyLlFY", title: "Why Haven't I Been Doing This the Entire Time?" }, { id: "O8ukIUoinhw", title: "Choosing the Right Vehicle on the Road to Life-Work Harmony" }, { id: "7o8LbFcGnOQ", title: "Time to be the proactive trusted advisor" }, { id: "xWIZGL5Bib8", title: "How to get off the 'treadmill'" }, { id: "Piz0uLcTs2I", title: "A key to increasing your income per hour" }] },
  { id: "consistency-accountability-and-process", name: "Consistency, Accountability & Process", description: "The importance of daily consistency, building accountability structures, following proven processes, and the compounding effect of showing up with discipline every day.", videoCount: 17, icon: "RefreshCw", gradient: "from-slate-500 to-gray-600", featuredVideos: [{ id: "BzJVYKK9uW8", title: "Power of Process" }, { id: "ja8Iu1xc2_4", title: "Why follow a process?" }, { id: "MHIRCf5G1Xo", title: "Consistently Showing Up to Practice with Ninja Systems" }, { id: "2GWGk4kgKac", title: "Consistency, Commitment, and Success by the Numbers" }, { id: "9zmn7PbS6Zc", title: "The Power of Process" }] },
  { id: "seller-process-and-listing-strategies", name: "Seller Process & Listing Strategies", description: "Listing consultations, strategic pricing, pre-listing packets, managing seller expectations, navigating pricing conversations, and the step-by-step Ninja seller process.", videoCount: 15, icon: "Home", gradient: "from-amber-500 to-orange-600", featuredVideos: [{ id: "8KlbnMzRmRQ", title: "Navigating Seller Risk: A Modern Approach to Pricing" }, { id: "bYnWVpkeZHs", title: "The Keys to Successful Listing Consultations" }, { id: "ly9r2hU_iy0", title: "Negotiating Sellers' Specific Financial Expectations" }, { id: "awpCk4zyd3g", title: "The Power of Strategic Pricing" }, { id: "8b-KmXHYijA", title: "Solve for Price" }] },
  { id: "conversations-questions-and-ford", name: "Conversations, Questions & FORD", description: "The FORD method (Family, Occupation, Recreation, Dreams), asking powerful questions, deep listening, conversation starters, and the art of meaningful dialogue that builds relationships.", videoCount: 15, icon: "MessageCircle", gradient: "from-sky-500 to-blue-600", featuredVideos: [{ id: "NyGbnpFRy24", title: "The Art of the Question: Next-Level Conversations" }, { id: "tgFqhzIMZTU", title: "Holiday Conversations That Actually Matter" }, { id: "Y8Vss_uaNl8", title: "How to Turn a Dream into a Reality" }, { id: "TVSjxqel9Ns", title: "Why Bother Asking? (You Should!)" }, { id: "YXjDBlk1mVc", title: "Dream It. Plan It. Do It. Celebrate It." }] },
  { id: "buyer-process-and-strategies", name: "Buyer Process & Strategies", description: "The Ninja buyer process, buyer consultations, creating buyers, working with offers, and strategies for guiding buyers through their home purchase journey.", videoCount: 14, icon: "ShoppingCart", gradient: "from-lime-500 to-green-600", featuredVideos: [{ id: "c16wsJZjPeE", title: "Why use the 10 step buyer process?" }, { id: "TRHFbYodxvA", title: "The Pivot from Buying Leads to Building Relationships" }, { id: "8YxCBDQCaeo", title: "Winning an offer without bidding the highest price" }, { id: "L1wX3OrOjsY", title: "Unlocking Homeownership: It's Not Just About Income" }, { id: "4TBBZBzr2rA", title: "Opening Up Inventory with Contingent Offers" }] },
  { id: "database-and-contact-management", name: "Database & Contact Management", description: "Building, managing, rating, and leveraging your contact database and CRM systems, hot/warm/cold list strategies, and the 50 live interviews concept.", videoCount: 13, icon: "Database", gradient: "from-violet-500 to-purple-600", featuredVideos: [{ id: "JD17rt5YqfE", title: "Unlocking the Power of Your Hot and Warm List" }, { id: "INs9lxeeLrg", title: "Building Your Warm List" }, { id: "fOMLGwibbuc", title: "Crack the Code on Your Database" }, { id: "xCMEE8zORRk", title: "What is the best CRM?" }, { id: "C5DRuM0xV8U", title: "Your 50 Live Interviews" }] },
  { id: "notes-calls-and-outreach-methods", name: "Notes, Calls & Outreach Methods", description: "Phone call techniques, handwritten notes, electronic notes, communication strategies, text messaging best practices, and multi-channel outreach approaches.", videoCount: 13, icon: "Phone", gradient: "from-pink-500 to-rose-600", featuredVideos: [{ id: "cA79L9ActJM", title: "The Power of Handwritten Notes in a Digital World" }, { id: "ybOd55CEfLw", title: "Why You're Hesitating to Reach Out" }, { id: "k4sTso2LEBM", title: "Unearthing the Beet and Potatoes of Successful Phone Calls" }, { id: "MtjcfMhP4mQ", title: "Phone Calls, Texts, and Effective Communication" }, { id: "7Q1hqszLJ4M", title: "Use this trick when making a phone call" }] },
  { id: "team-building-and-leadership", name: "Team Building & Leadership", description: "Building and leading real estate teams, developing company culture, hiring and mentoring, team structures, and leadership development for real estate professionals.", videoCount: 13, icon: "Users", gradient: "from-fuchsia-500 to-purple-600", featuredVideos: [{ id: "O-FuU1mRUbc", title: "How to Build a Team That Actually Works" }, { id: "kTDF9KQJjKw", title: "Building a Thriving Team and Business with John Newman" }, { id: "GVD4Kr0x3j4", title: "How to Build a Ninja Company: A Blueprint from Jenny Usaj" }, { id: "guptRmiGo0I", title: "How to Effectively Hand Off Your Real Estate Business" }, { id: "26fFCYtAu9s", title: "The Team Leader Blueprint" }] },
  { id: "success-stories-and-case-studies", name: "Success Stories & Case Studies", description: "Real-world success stories from Ninja practitioners, impressive production numbers, transformational journeys, and case studies that demonstrate the Ninja Selling system in action.", videoCount: 10, icon: "Trophy", gradient: "from-yellow-500 to-amber-600", featuredVideos: [{ id: "LoRzDXnzgDI", title: "How a Rookie Did $28M in His First Year" }, { id: "enPY66udOro", title: "From $8,000 a Year to $308,000 a Year in Five Years" }, { id: "3iLTcuHEQ-Y", title: "From Classroom to Closing: A College Course Launched a Ninja Career" }, { id: "9JWJz5pf0Rk", title: "The Ninja Couple: From Military Precision to Real Estate Success" }, { id: "tUYd92RyZ_E", title: "The $1 Million Secret with Amy Balewicz" }] },
  { id: "prospecting-and-lead-generation", name: "Prospecting & Lead Generation", description: "Lead generation strategies, networking techniques, building your sphere of influence, community involvement, and organic prospecting that aligns with the Ninja philosophy.", videoCount: 9, icon: "Search", gradient: "from-red-500 to-rose-600", featuredVideos: [{ id: "0yQI3bcSrBo", title: "The best lead generation activity ever!" }, { id: "cYEukn_34Uw", title: "Building a Tribe: Lessons in Community and Success" }, { id: "WAUbcNRqo5k", title: "Dunbar's Number and Building Your Tribe" }, { id: "_9s1laeiYGo", title: "Best Lead Generation Activity" }, { id: "GLmCFotxmEY", title: "Getting to Know Your Vendors" }] },
  { id: "real-estate-reviews-and-presentations", name: "Real Estate Reviews & Market Presentations", description: "Creating and hosting real estate review events and market update presentations to position yourself as the trusted advisor in your market.", videoCount: 8, icon: "BarChart3", gradient: "from-teal-500 to-emerald-600", featuredVideos: [{ id: "FTwYZnYdBXY", title: "Harnessing the Power of Data and Real Estate Reviews" }, { id: "zvXLZyR2nD4", title: "Turning Real Estate Reviews into Transactions" }, { id: "FGlj1Okm6Gk", title: "Perfecting Real Estate Reviews for Today's Marketplace" }, { id: "NkAFeWfAq5E", title: "Announcing the Monthly Ninja Sales Meeting" }, { id: "ge6ZluujyzI", title: "The steps in MLS to prepare a RER" }] },
  { id: "value-service-and-client-experience", name: "Value, Service & Client Experience", description: "Delivering exceptional value, creating memorable client experiences, fabled service, and going above and beyond to make clients feel genuinely cared for.", videoCount: 7, icon: "Star", gradient: "from-amber-500 to-yellow-600", featuredVideos: [{ id: "oVLNmVuyVtU", title: "Creating a Positively Unique Experience for Your Clients" }, { id: "gcR4KkChDlU", title: "For Ninjas creating Fabled Service is everything" }, { id: "p15YL4syGZI", title: "Be the source of information" }, { id: "q2mIWrCDK2E", title: "Setting Yourself Apart from the 'Order Takers'" }, { id: "TW4fLeFqS4M", title: "What Exactly Does My Client Want?" }] },
  { id: "branding-marketing-and-technology", name: "Branding, Marketing & Technology", description: "Building your personal brand, video marketing, leveraging technology, digital presence, and using tools to enhance (not replace) your relationship-based business.", videoCount: 6, icon: "Megaphone", gradient: "from-blue-500 to-cyan-600", featuredVideos: [{ id: "ayVN-nf5D2I", title: "Delivering Peace of Mind with Step-by-Step Tech" }, { id: "YiPqjNy6ao8", title: "Showcasing Your Value in the Digital Age" }, { id: "ZMwUiUZtFVI", title: "Postcards: Doing Them the Right Way" }, { id: "Y4VeVAy4uOM", title: "Video Makes the Real Estate Star" }, { id: "VKJd7NCwWts", title: "A Couple Amazing QR Code Tools" }] },
  { id: "negotiation-and-transaction-management", name: "Negotiation & Transaction Management", description: "Negotiation techniques, managing complex transactions, handling the NAR settlement, and guiding clients smoothly from contract to close.", videoCount: 5, icon: "Scale", gradient: "from-gray-500 to-slate-600", featuredVideos: [{ id: "GSzVzqoGREA", title: "Mastering the Art of Negotiation" }, { id: "zctlvR61c3w", title: "Navigating the NAR Settlement like a Ninja" }, { id: "sJPBmkyqHZk", title: "Piecing Together the Transaction Puzzle" }, { id: "Np43CvzpxyI", title: "Negotiate Home Plate" }, { id: "qLbAcnTrxEA", title: "Acceptance Stage Management" }] },
  { id: "covid-19-and-crisis-response", name: "COVID-19 & Crisis Response", description: "Content addressing the COVID-19 pandemic and how real estate agents can adapt their Ninja practices during times of crisis and uncertainty.", videoCount: 4, icon: "ShieldAlert", gradient: "from-red-500 to-orange-600", featuredVideos: [{ id: "eyt9klIATyM", title: "Larry Kendall's COVID-19 Response" }, { id: "zr2wR0vWxNA", title: "Ninjas and COVID-19" }, { id: "GjxTaOTgbVw", title: "More Ninja Ideas around COVID-19" }, { id: "QoxskHww5kE", title: "Physical distancing not social" }] },
  { id: "open-houses", name: "Open Houses", description: "Strategies and best practices for conducting successful open houses as a lead generation and relationship-building opportunity.", videoCount: 2, icon: "DoorOpen", gradient: "from-green-500 to-emerald-600", featuredVideos: [{ id: "PmkSXY3o6L8", title: "Strategy Session to Upgrade Your Open Houses" }, { id: "PprswnVmwqk", title: "Reaping the Rewards of Open Houses" }] },
]

export const allVideos: Video[] = [
  { id: "4qMoGTx4b0Y", title: "Action Tip #579: Handle hard better with the right team!" },
  { id: "O-FuU1mRUbc", title: "How to Build a Team That Actually Works" },
  { id: "Jd3U-Lcs4b8", title: "Action Tip #578: Done is Better Than Perfect" },
  { id: "NYIhCLe-ZFo", title: "Why 'Flow Fixes Everything' in Real Estate" },
  { id: "r1QbMt3Xjto", title: "Auto-Flow 101: Why Flow Fixes Everything" },
  { id: "YXjDBlk1mVc", title: "Action Tip #577: Dream It. Plan It. Do It. Celebrate It." },
  { id: "T4Gh5UuotBc", title: "Don't Forget to Have Fun" },
  { id: "TRHFbYodxvA", title: "The Pivot from Buying Leads to Building Relationships" },
  { id: "fTZmX-Cgw9U", title: "Bonus Episode: The Gold is in the Ghosts Sales Meeting" },
  { id: "LCel0MB8Bw0", title: "Stop Selling. Start Solving. The Second Cornerstone of Ninja Selling" },
  { id: "ybOd55CEfLw", title: "Action Tip #575: Why You're Hesitating to Reach Out" },
  { id: "n-_1Xu5ZUpY", title: "Rebuilding on Purpose Through Flow" },
  { id: "JAgIsaRpZ5c", title: "The Ninja Scorecard - Your Plan for Consistency" },
  { id: "bWObJe8cwbc", title: "Action Tip #574: Detach from the Outcome" },
  { id: "eE1qHKc-B6o", title: "From the Hamster Wheel to Deep Connections" },
  { id: "VekdkcTX5uE", title: "Best Year Yet in Brooklyn" },
  { id: "nTnsOdVZmao", title: "Action Tip #572: Did You Make a Reservation" },
  { id: "MJfKBiQJZpk", title: "This is Happening For Me, Not To Me" },
  { id: "WC_nezGrWJ4", title: "Live From The Ninja Installation: Trust the Process, Then Watch the Results" },
  { id: "IS1470U8xiM", title: "What is Personal Mastery in Ninja Selling?" },
  { id: "4lwMtg1zP18", title: "Personal Mastery: The First Cornerstone of Ninja" },
  { id: "ElBtOoFanoE", title: "Action Tip #570: Flip the Switch" },
  { id: "ropiLhLsfk0", title: "If You Could Wave Your Magic Wand" },
  { id: "49PhQ8nwzjM", title: "Action Tip #568: This Simple Action Creates Referrals (and it’s Not Selling)" },
  { id: "Bvqzlo3M4CU", title: "Action Tip #567: Your 2026 Word of the Year" },
  { id: "2WKDpsTEOTY", title: "Ninja In A Nutshell - An Overview of the Ninja Selling System" },
  { id: "tgFqhzIMZTU", title: "Action Tip #566: Holiday Conversations That Actually Matter" },
  { id: "9OR8ztxjifs", title: "Momentum Isn't Loud - It's Consistent" },
  { id: "qzT4SZFcv_k", title: "Action Tip #565: Create Your Holiday 8×8" },
  { id: "0NX-NQDh3Ng", title: "20 Hours. 100 People. Zero Burnout." },
  { id: "euuyZhIeP2M", title: "Action Tip #563: A Thanksgiving Action Tip That Could Make Someone’s Week" },
  { id: "yu_7yzbLHfU", title: "How To Be Consistently Magnetic Even When Life Throws You A Curve Ball" },
  { id: "LZ0Bq043RRs", title: "Action Tip #562: While Others Coast, Ninjas Double Down" },
  { id: "9JWJz5pf0Rk", title: "The Ninja Couple: From Military Precision to Real Estate Success" },
  { id: "APK1mycdSM0", title: "Action Tip #561: This Economic Indicator Could Be Your Next Opportunity" },
  { id: "Bt0I1piZ71I", title: "\"Do I Pursue a Solo Career Or Do I Form a Team?\"" },
  { id: "Rk_yvHdW0ys", title: "How to Intentionally Create Change" },
  { id: "vEooMYXxK3Y", title: "Action Tip #559: Don't Miss the Assembly" },
  { id: "N4EbHY3j-KM", title: "80 Years Worth of Stellar Advice for Today's Agent" },
  { id: "tp3-f7IfZNI", title: "Action Tip #558: Finish Strong by Reviewing What Worked (and What Didn’t)" },
  { id: "MO_CPEilpfw", title: "How to Have Consistent Volume in an Inconsistent Market Using Consistent Routines" },
  { id: "5PjAt7AESSA", title: "Action Tip #557: Guide With Clarity...Not Fear" },
  { id: "Y8Vss_uaNl8", title: "How to Turn a Dream into a Reality" },
  { id: "1lxD6ibUcG0", title: "Mastering the Ninja Planner with Creator Eric Hardy" },
  { id: "7K8UEtNcqHs", title: "From Burnout to Breakthrough: Lonney Gordon's Journey to Authentic Flow" },
  { id: "K08vG_LKc9o", title: "Action Tip #555: Now is the time." },
  { id: "epKxHFOiELA", title: "Throw Out the Rulebook: Opportunity Inside the Compass x Anywhere Real Estate Merger" },
  { id: "D5A55uPxzTY", title: "The Opportunities in Change - Larry Kendall, Jack Miller, Mike Staver" },
  { id: "5rzPb10nqKo", title: "Action Tip #554: Farmers don’t just plant… they prepare" },
  { id: "Yui0U6Un3l0", title: "From Travel Crisis to Real Estate Fortune" },
  { id: "k1n86XHg3Pk", title: "Action Tip #553: People Hire How They Feel Around You" },
  { id: "lvFwUzy81Lc", title: "Ninja Hacks for Exponential Growth with Martin Gallant" },
  { id: "hq94Ishz1A8", title: "Sell Your Stalled Listing with a Seller's Offer" },
  { id: "szgSkjzwKSg", title: "Action Tip #551: Double Down on Gratitude" },
  { id: "lQV3q7XJ7_0", title: "Simple Shifts for a More Profitable Business" },
  { id: "qv9Rt4-LWE4", title: "Action Tip #550: 30 Minute Morning Reset" },
  { id: "VFJZeD6iWU8", title: "Building Unshakable Confidence for Real Estate Agents" },
  { id: "bWNfhLrXpgs", title: "Action Tip #549: Make the Shift from “A Realtor” to “My Realtor”" },
  { id: "3iLTcuHEQ-Y", title: "From Classroom to Closing: How a College Course Launched a Ninja Career" },
  { id: "iW01Yxeptaw", title: "Action Tip #548: Tune in to Opportunity" },
  { id: "MBRDeWUphrc", title: "Are You Creating Buyers?" },
  { id: "5DmxfgQVyko", title: "Matthew Gardner's Housing Market Talking Points" },
  { id: "LoRzDXnzgDI", title: "How a Rookie Did $28M in His First Year: Koby Bishop's Blueprint for Success" },
  { id: "v7ZiyYl70YA", title: "Action Tip #546: Neighbor Notes for Your Buyers" },
  { id: "_4yJOO4iWxQ", title: "Your Mid-Year Halftime Huddle" },
  { id: "2uwdfYghEcU", title: "Action Tip #545: Start Your Stop Doing List" },
  { id: "hxf_xfuVBkM", title: "Mastery of Yourself" },
  { id: "NyGbnpFRy24", title: "The Art of the Question: Next-Level Conversations with Erik Zimmerman" },
  { id: "Vyq2tnJynyQ", title: "Action Tip #544: Use Ninja on Your Most Important Client" },
  { id: "azOsX53XCSU", title: "Ninja Selling Guide Camp" },
  { id: "5LcsTudzveU", title: "The Reverse Offer" },
  { id: "9TrLAqEFUbw", title: "Action Tip #543: The Reverse Offer (aka Offer to Sell)" },
  { id: "AGpbzfWbJFo", title: "Larry Kendall's Summer Plans" },
  { id: "T1uRJ0n26CM", title: "Action Tip #542: Build Your \"Notes On The Go\" Kit" },
  { id: "GVD4Kr0x3j4", title: "How to Build a Ninja Company: A Blueprint from Jenny Usaj" },
  { id: "fge6q4Qbgj8", title: "Frictionless Referrals: Introducing Referral Flow and the New Find a Ninja" },
  { id: "HhkVvydPVDw", title: "Action Tip #541: On a Scale Of 1-10" },
  { id: "LpuIOdDIxWU", title: "How To Be a Resort Market Ninja" },
  { id: "0bFRFS8cIlU", title: "Action Tip #540: Know the Best Deal in Your Market" },
  { id: "26fFCYtAu9s", title: "The Team Leader Blueprint - by Ninja Coaching" },
  { id: "NkAFeWfAq5E", title: "The Return of the Sales Meeting: Announcing the Monthly Ninja Sales Meeting with Larry Kendall" },
  { id: "IptK2wttAR0", title: "Action Tip #539: Power Your Summer Flow" },
  { id: "-1tQZNgfYS0", title: "June Live Action Tip: How’s the market?" },
  { id: "Qme0HO1Q5G0", title: "Create More, Work Less" },
  { id: "8KlbnMzRmRQ", title: "Navigating Seller Risk: A Modern Approach to Pricing Conversations" },
  { id: "kTDF9KQJjKw", title: "The Heart of a Ninja: Building a Thriving Team and Business with John Newman" },
  { id: "61Tp0OD0B8s", title: "Action Tip #538: Pricing Right" },
  { id: "Vr0tsN3zPPs", title: "Action Tip #537: Referral Flow" },
  { id: "enPY66udOro", title: "How to Go From Earning $8,000 a Year to $308,000 a Year in Five Years" },
  { id: "PmkSXY3o6L8", title: "May Ninja Kickoff: 20-Minute Strategy Session to Upgrade Your Open Houses" },
  { id: "tRFe9Z1vKC8", title: "Your Ninja Nine Challenge with Julianne Rawlins" },
  { id: "eohkaXms_H4", title: "Action Tip #536: Know Your Numbers" },
  { id: "ihzeS_VUaQ0", title: "A Community of Raving Fans" },
  { id: "LtF7nlt2lYk", title: "The Level Up Moment: Leading with Mindset, Skillset, and Action featuring Jennifer Lind" },
  { id: "9ltHuRBZXqE", title: "Shift Your Mindset with One Sheet of Paper" },
  { id: "FZ-VDXl7X0s", title: "Action Tip #535: Deepen Any Relationship" },
  { id: "vkJb4QQyOXM", title: "Live Action Tip Webinar: Clarity is Power" },
  { id: "cYEukn_34Uw", title: "Building a Tribe: Lessons in Community and Success from a 50-Year Rock Band" },
  { id: "L1wX3OrOjsY", title: "Action Tip #534: Unlocking Homeownership: It's Not Just About Income." },
  { id: "o00RZgceB2s", title: "Tripling Your Business: Jim Knight on Mindset, Skillset, and Action" },
  { id: "vAM7IZDYTUc", title: "Action Tip #533: The One-Two Punch To Transform Your Flow" },
  { id: "6V0uatxS_XM", title: "Springtime Mojo" },
  { id: "OEzhhzJL2CU", title: "Action Tip #532: Electronic Notes" },
  { id: "kF7uqtedbG0", title: "Find Your Pickleball" },
  { id: "Np43CvzpxyI", title: "Action Tip 531: Negotiate Home Plate" },
  { id: "qKRDyrp5aoc", title: "Tales from the Road: Insights and Opportunities in Today's Real Estate Market" },
  { id: "BI0wFgSwxZA", title: "Action Tip #531: Pre-Listing Packets ( March Kickoff)" },
  { id: "K3rF7rrs0rg", title: "From Snowboarder to Ninja: First Impressions from the Ninja Installation" },
  { id: "v54aGsu26Xs", title: "Action Tip #530 Deliver Confidence And Clarity" },
  { id: "tUYd92RyZ_E", title: "The $1 Million Secret with Amy Balewicz" },
  { id: "NWkrSvWHoJ8", title: "Action Tip #529: The Gap And The Gain" },
  { id: "9IrI5eCIGNg", title: "The Secret to Guilt-Free Client Follow Up" },
  { id: "MrrcmrIzmKg", title: "Action Tip #528: Be Referable" },
  { id: "JD17rt5YqfE", title: "Unlocking the Power of Your Hot and Warm List: Strategies from Joe Robert and Mark Johnson" },
  { id: "INs9lxeeLrg", title: "February 2025 Kickoff Webinar: Building Your Warm List" },
  { id: "zvXLZyR2nD4", title: "Turning Real Estate Reviews and Events into Transactions with Lori Chamberlain and Lisa Connors" },
  { id: "kE_KsbmJBng", title: "Become the CEO of Your Relationships with Meaghan Austin" },
  { id: "guptRmiGo0I", title: "How to Effectively Hand Off Your Real Estate Business" },
  { id: "kLf6JsfYWKM", title: "Bounce Back" },
  { id: "Nw0jmMDwjoA", title: "What's Your 2025 Word of the Year?" },
  { id: "95-QBhCjZwo", title: "Make 2025 Your Best Year Ever in Real Estate" },
  { id: "v9qteF2VDx8", title: "Holiday Flow Ideas" },
  { id: "UedLGJTp9KU", title: "Want More Closings? Master Your PIE Time" },
  { id: "7e1YLIXy0Vs", title: "Ninja Selling November 2024 Kickoff Call" },
  { id: "6TyrS31knKs", title: "Business Planning" },
  { id: "sp2ZOTql8lM", title: "The Secret To Effortless Real Estate Referrals" },
  { id: "zmXDMX3y84A", title: "A Servant's Heart" },
  { id: "k5IydNtQNxU", title: "The Winter Soldier" },
  { id: "j3leXdBn0BY", title: "Trying Something New" },
  { id: "0L1zmWMwvaE", title: "Ninja Installation Takeaways You Need To Know" },
  { id: "n9ne29mfYyw", title: "Become a Top Producer With THIS Mindset" },
  { id: "wYvdilqyLWY", title: "Larry Kendall Answers Your Questions" },
  { id: "-QLdV8uPtZE", title: "How to Finish 2024 Strong and Set Up for 2025 Success" },
  { id: "Zp3tEpdV6C0", title: "NOLA Property Guys Explain the Real Estate Vibe Check" },
  { id: "c7Z6owTLHgc", title: "Why This Realtor Doesn't Fear Market Shifts" },
  { id: "tJYZAah4q_M", title: "How Jonathan Spears Built A $500M Team" },
  { id: "qrYXzXjavVw", title: "He Wrote The Book On A Drama Free Life" },
  { id: "WxPQzM6iqTU", title: "Video Version - How To Generate Referrals Without Asking with Larry Kendall and Stacey Brown Randall" },
  { id: "NxnbMw5jymE", title: "How To Generate Referrals Without Asking" },
  { id: "AoJim8CbTzg", title: "5 Questions That Turn Conversations Into Clients" },
  { id: "xCMEE8zORRk", title: "Action Tip #505: What is the best CRM?" },
  { id: "TVSjxqel9Ns", title: "Why Bother Asking? (You Should!)" },
  { id: "TUSgP6pL-Ho", title: "The Ninja Selling Podcast Episode 586 / Ninja Coaches: Why Agents Use Them To Win" },
  { id: "dRXTDAfGp70", title: "Ninja Coaches: Why Agents Use Them To Win" },
  { id: "YViDcHmX2-0", title: "Action Tip #503: Revisit the Tools You Already Have" },
  { id: "ar5xPA6PlKg", title: "Action Tip #502: Track Your Ninja Nine" },
  { id: "bRbIAV1e_C8", title: "The Future Of Ninja Selling Revealed" },
  { id: "EX_26NqI8oU", title: "Ninja Action Tip #499: The Problem is the Solution" },
  { id: "EwAqaEdg3eE", title: "The Opportunity Ahead with Garrett, Matt, & Larry" },
  { id: "FsYR0TRBa5Q", title: "Weekly Action Tip #498: If They Say It - They Own It" },
  { id: "maMPuSTFUVQ", title: "Over 3.5 Million Downloads Later: What We've Learned" },
  { id: "JUm8tBd6gLg", title: "Seeing the Change on the 15th Day" },
  { id: "g1DjyqhZz4g", title: "Building Your Dreamer Teams" },
  { id: "890H9U9E-SA", title: "\"Your Opportunity in Your Hands Right Now!\"" },
  { id: "qGhHgySUNV4", title: "Maintaining \"I\" Contact" },
  { id: "84aIEIGr5Z4", title: "Be the Brand" },
  { id: "dFN_kwG_mAM", title: "Local Area Networking" },
  { id: "wIWIPzUTMyU", title: "Your Ideal Customer" },
  { id: "mZAWJLUCUkc", title: "Put Your Feet Down" },
  { id: "gyTv6IyLlFY", title: "Why Haven't I Been Doing This the Entire Time?" },
  { id: "1C5CW_jxx7c", title: "Communication Elevation" },
  { id: "h0dDjyF32Eg", title: "Recognizing Opportunity's Knock" },
  { id: "MzNpTmo6Lf4", title: "Keeping Time on Your Side" },
  { id: "5bQJqtRTxtE", title: "Taking the Lead" },
  { id: "XK9zerTF4-Y", title: "Thawing Out the Information Overload Freeze" },
  { id: "RxENbmZtSeU", title: "Learning That It's Awkward Until It's Not" },
  { id: "ftqxEQvV0M0", title: "Ninja Coaching Spotlight with Christine Moore and Tracy Peterson-Nienaber" },
  { id: "7U0_aVWhjTk", title: "Knowing When to Raise the Bar" },
  { id: "IC3rQM9LbCU", title: "Growing with the Flow" },
  { id: "Pwgg1WvhiBI", title: "One For the History Books" },
  { id: "r7HkJjS27T0", title: "Maintaining the Personal Touch in a Digital Age" },
  { id: "2scB4wEORNs", title: "\"Please Stop Predicting the Future\"" },
  { id: "zctlvR61c3w", title: "Navigating the National Association of REALTORS® Settlement like a Ninja" },
  { id: "eiDjJkgyJfU", title: "\"Houston, We Have an Opportunity\"" },
  { id: "gOb5KWsM9Vg", title: "Riding The Routine Road to Success" },
  { id: "dPj3i1HSGKU", title: "Energy Management for Client Engagement" },
  { id: "BKgsYbjJmU4", title: "Free Time vs. Fun Time" },
  { id: "-GvT0jBhB8c", title: "Ninja Coaching Spotlight with Patty Schmitz-Thursam and Natalie Davis" },
  { id: "zA_fJFIhUec", title: "\"Whenever You Win, People Will Immediately Assume…\"" },
  { id: "mADUAeTtgAU", title: "\"This Is Why Ninja Was Built\"" },
  { id: "-AETTR50jfg", title: "Playing The Long Game" },
  { id: "UKHSxpDnKHg", title: "It's Not Just About Numbers" },
  { id: "u_BjOm8VI04", title: "Ninja Coaching Spotlight with Travis Beers and Jon Hill" },
  { id: "k4sTso2LEBM", title: "Unearthing the Beet and Potatoes of Successful Phone Calls" },
  { id: "3CgVWorsQ38", title: "Ninja Action Tip #486: Schedule a Meeting with Yourself" },
  { id: "tvAgwEuT1oA", title: "Trust Never Sleeps" },
  { id: "2GWGk4kgKac", title: "Consistency, Commitment, and Success by the Numbers" },
  { id: "FgXHdIZC6KE", title: "Ninja Action Tip #485: You are the Quarterback" },
  { id: "eK3DBHn3GiI", title: "Achieving Balance in a 24/7 Industry" },
  { id: "PevRygUYj-I", title: "Ninja Coaching Spotlight with Joan Goode and Jen Gamez" },
  { id: "66GiOZ9elH0", title: "Critical Calendar Control" },
  { id: "VKJd7NCwWts", title: "A Couple Amazing QR Code Tuells" },
  { id: "VpEyXIfUOqY", title: "Managing the Busy in Your Business" },
  { id: "xgIUPX5Cee8", title: "Fulfilling the New Year's Promise" },
  { id: "xXePRJRourQ", title: "Ninja Coaching Spotlight with Lonney Gordon and Jen Fidler" },
  { id: "RZuRm_wcchs", title: "Taking Care of the Upstream" },
  { id: "GLmCFotxmEY", title: "Getting to Know Your Vendors" },
  { id: "ik7m9TWp5Kk", title: "Leaning into Lifelong Learning" },
  { id: "pSttNDhWSxU", title: "It's Stop Blocking and Start Depositing Time" },
  { id: "NTsUTd6p0Ok", title: "Ninja Coaching Spotlight with Christina O'Neal and Mark Johnson" },
  { id: "wXxKGuVdakY", title: "Fostering Growth by Embracing Change" },
  { id: "b5FL-jLqMcs", title: "Managing Interest Rate Perceptions" },
  { id: "kUlREjzMBf4", title: "Close Encounters of the Most Memorable Kind" },
  { id: "A2HS-XC2lHs", title: "Kicking Off 2024 with the \"Digital Commute\"" },
  { id: "wTnD6ZFT0-4", title: "Ninja Coaching Spotlight with Alice Toy and Jen Gamez" },
  { id: "T578Wr8oYo4", title: "Little Improvements That Generate Big Success" },
  { id: "Q9Zyi6GhFgw", title: "Celebrating Every Day" },
  { id: "dxY5eN8tqJg", title: "Get the Skills Group Scoop" },
  { id: "_es7afdNUT4", title: "Becoming the Market Expert" },
  { id: "5ZJw0tgXyb8", title: "Ninja Coaching Spotlight with Abby Baker and Heather Matz" },
  { id: "AZ2IUWj9Zt8", title: "Embracing an Attitude of Gratitude with Mr. Thank You" },
  { id: "DcqndNk7xSI", title: "Taking Zero Off the Table" },
  { id: "Y7Tr6O0W4Zs", title: "What's Your Money Up To?" },
  { id: "WyGAcuzg-cw", title: "\"One of Three Things\" with Larry Kendall" },
  { id: "RQuYhWYphHk", title: "Ninja Coaching Spotlight with Susan Saving" },
  { id: "WNHWvneMbjY", title: "Ninja Installation Q&A with Dennis Giannetti" },
  { id: "GeXsrTdDJXY", title: "Wisdom, Guidance, and Reassurance from Larry Kendall" },
  { id: "taBkLlwdCn8", title: "Happy Thanksgiving from Ninja Selling!" },
  { id: "M8tvXIRwOnk", title: "Navigating Life's Curveballs" },
  { id: "Mdn11Bsk1IM", title: "Ninja Coaching Spotlight with Melissa Herdman" },
  { id: "padu2VJmRYw", title: "Defining Your Own Success" },
  { id: "LQsmLafvj5s", title: "Keep the Selling Homes Fire Burning" },
  { id: "sEwSnIBmt3w", title: "\"To Thine Own Self Be True\"" },
  { id: "hMqiTvVwZik", title: "The Power of Presence in Your Clients' Worlds" },
  { id: "yo9UZwm61AQ", title: "Ninja Coaching Spotlight with Michael Doyle" },
  { id: "iRBxDL_r10s", title: "Understanding and Outperforming the Market" },
  { id: "WZfToQUja7Y", title: "Planning for Even Greater Success in 2024" },
  { id: "TwnUSZBQieY", title: "Making Positive Waves with the Law of Precession" },
  { id: "MmJYhYTLIWo", title: "Whose Goal Are You Chasing?" },
  { id: "09Qjx1kgIbw", title: "Ninja Coaching Spotlight on Allie Hatley and Lisa Connors" },
  { id: "p5rxnJ0lYSg", title: "Feasting on Balance and Sustainability" },
  { id: "_D4z-OOqrPA", title: "Baking Success into Your Business Cake" },
  { id: "ANUWqpbSDq4", title: "Gifting Yourself Presence" },
  { id: "GSzVzqoGREA", title: "Mastering the Art of Negotiation" },
  { id: "1SRiwYN1114", title: "Ninja Coaching Spotlight on Renee Bert and Mary-Clare Hill" },
  { id: "t1NgbYAkIVo", title: "Expectations, Communication, and Reputations" },
  { id: "xBb-y1zRHsM", title: "The Big 5-0-0!" },
  { id: "TC6Ta7BsUzI", title: "Balancing Passions and Obligations" },
  { id: "gVF4tckHw5I", title: "Waking Up to Success" },
  { id: "8-B8RO455ME", title: "Ninja Coaching Spotlight on Peggy Shanklin and Shelly Culbertson" },
  { id: "4TBBZBzr2rA", title: "Opening Up Inventory and Opportunity with Contingent Offers" },
  { id: "px3xQjl_oJA", title: "Celebrating Realtor Safety Month with Natalie Davis" },
  { id: "S2_v8-wrAo0", title: "Speaking of Dreams" },
  { id: "ZMwMzNic2oM", title: "Dream a Little Dream" },
  { id: "hLAFZMMcaHA", title: "Introducing The Ninja Coaching Spotlight" },
  { id: "wBIRkcmEwxo", title: "When You Want It More Than the Client Does" },
  { id: "GaBzpaS3_Ts", title: "Accelerating Your Business Machine on the Straightaways" },
  { id: "JyBZsfA1VCg", title: "What Are the Pros and Cons of the 30 Year Mortgage?" },
  { id: "gqmT49Mz5yE", title: "The Confusion Solution" },
  { id: "jjy2-zZq4VU", title: "Choosing Sustainable Success Over Quick Fixes" },
  { id: "Y9_wEmE_SPQ", title: "Been There, Done That" },
  { id: "Qeb0N_idgaM", title: "Firing Up the 'Long-Term Machine'" },
  { id: "zpfJpZEzLMM", title: "The Ripple Effect of Effortless Information Access" },
  { id: "BGE04tKHcww", title: "\"Let's Make It Really Simple\"" },
  { id: "4OsMj06CZ0Y", title: "Going that Extra Mile on the Road to Success" },
  { id: "0PJvFD2FVtQ", title: "Taking this Time to Sharpen Your Skills" },
  { id: "awpCk4zyd3g", title: "The Power of Strategic Pricing" },
  { id: "q2mIWrCDK2E", title: "Setting Yourself Apart from the 'Order Takers'" },
  { id: "tV3mHE4MUKA", title: "Grow with the Flow" },
  { id: "-OQtRCUxVmc", title: "Tapping into Collective Wisdom" },
  { id: "sJPBmkyqHZk", title: "Piecing Together the Transaction Puzzle" },
  { id: "29QV5yG5hXE", title: "Goal Pacing Your Way to a Successful Year" },
  { id: "Gil3ipcxC6o", title: "The Uplevel is in the Details" },
  { id: "3Ab9ziXAWH8", title: "Keep Your Engine Tuned" },
  { id: "GP65V2uhckk", title: "Moving Clients Off the Fence and Into a House" },
  { id: "6dAKOAO3yKs", title: "Giving Your Family the Credit They Deserve" },
  { id: "1tZ-oHhh-rw", title: "Welcome to the Redundancy Department of Redundancy" },
  { id: "AW-8Hk9KyqM", title: "Everyone Has to Pee" },
  { id: "3nwp3YhKsOk", title: "\"What's Going on in the Market?\"" },
  { id: "cA79L9ActJM", title: "The Power of Handwritten Notes in a Digital World" },
  { id: "QXg3CIRdgeA", title: "Maintaining Authenticity in an AI World" },
  { id: "O8ukIUoinhw", title: "Choosing the Right Vehicle on the Road to Life-Work Harmony" },
  { id: "cTcyAKSwHOI", title: "To Scale or Not to Scale" },
  { id: "ly9r2hU_iy0", title: "Negotiating Sellers' Specific Financial Expectations" },
  { id: "Bvy8Jr6fCzI", title: "When Good Properties Just Won't Sell" },
  { id: "5iBckOvnw38", title: "Increasing Your Return on Time" },
  { id: "D5PM7ePMvhc", title: "Pitching Coaches" },
  { id: "necbcQ7lLqs", title: "Finding Success in Flow Motion" },
  { id: "LGc_DR8ZVxI", title: "Debunking the Low Interest Rate Myth" },
  { id: "ayVN-nf5D2I", title: "Delivering Peace of Mind with Step-by-Step Tech" },
  { id: "Y4VeVAy4uOM", title: "Video Makes the Real Estate Star" },
  { id: "hMtYU96VORc", title: "Developing Dynamic Databases" },
  { id: "8LyxNuLuCXA", title: "Revving Up Your Systems" },
  { id: "MtjcfMhP4mQ", title: "Phone Calls, Texts, and Effective Communication" },
  { id: "VnZ6u1nWdb4", title: "Wake-Up Money with Larry Kendall" },
  { id: "aBaWQvQ6U1g", title: "Integrating Ninja into Your Existing System" },
  { id: "TW4fLeFqS4M", title: "What Exactly Does My Client Want?" },
  { id: "-XlMibSeayI", title: "Assistants Assistance with Shelley Culbertson" },
  { id: "TR27GMGffdI", title: "Using Fear of Judgment to Your Advantage" },
  { id: "oVLNmVuyVtU", title: "Creating a Positively Unique Experience for Your Clients" },
  { id: "wWXuHsHGDZ8", title: "Reigniting Your Passion" },
  { id: "owLVBw8cxS0", title: "Quality vs. Quantity" },
  { id: "Ssgc1LZQ-V4", title: "Value, Relationships, and Referrals" },
  { id: "6bO9frs44A8", title: "When Agents Sell Their Own Homes - The Bonelli Files" },
  { id: "OWLR9yHxuVA", title: "Balancing Emotional Attachment and Detachment" },
  { id: "X2PP_GJ_a5M", title: "When Your Client Is Both a Buyer and a Seller" },
  { id: "FAYy_dNvmoE", title: "Partnering for Success in Any Market: A Client's Perspective" },
  { id: "VdnEsx0U13s", title: "Achieving Sustainable Success" },
  { id: "-mLSYbZRTrs", title: "Getting the Gang Back Together Again" },
  { id: "2l_uJ-55POw", title: "Charging Up Your Hour of Power" },
  { id: "VrLqD8shRZ8", title: "Maintaining Your Balance when 'Drinking from a Fire Hose'" },
  { id: "bYnWVpkeZHs", title: "The Keys to Successful Listing Consultations" },
  { id: "dTw8orpkvzo", title: "Loved the Installation! Now What?" },
  { id: "WRL3etfFh1A", title: "The Ninja Perspective on Pop-Bys" },
  { id: "qLbAcnTrxEA", title: "Acceptance Stage Management" },
  { id: "YiPqjNy6ao8", title: "Showcasing Your Value in the Digital Age" },
  { id: "aAbcpV-V1C4", title: "Deciding to be Disciplined" },
  { id: "PrJQXXqm2lg", title: "The Secret to Success in Any Market" },
  { id: "CO1Fr19kH9s", title: "Reviewing Real Estate Reviews" },
  { id: "dgsy9cWNRMg", title: "Keeping Your Word" },
  { id: "nYXnTmvmG7w", title: "Fishing in Your Database" },
  { id: "o2qK4G4YthQ", title: "Minding Your Own Business" },
  { id: "Q5nHAivP0Us", title: "Flicking the Switch" },
  { id: "Jog4Seaftc0", title: "Step Into The Process" },
  { id: "WAUbcNRqo5k", title: "Dunbar's Number and Building Your Tribe" },
  { id: "IoR_F4tY_e4", title: "Channeling the Power of Self-Salesmanship" },
  { id: "wCQ1JAyv-oE", title: "Is Money Walking?" },
  { id: "RIdDMFSCZk8", title: "Personal Connection and World Perception" },
  { id: "msJDr0N7Pq8", title: "Self-Care: The Holiday Edition" },
  { id: "ZdDXXRleW58", title: "Customer Relationship Management Systems" },
  { id: "H3FIY9EFIB0", title: "Moving Goals from Realistic to Incredible" },
  { id: "BnGc8ZX3kKk", title: "Always Being There for Your Clients" },
  { id: "14o3seZuI4U", title: "Are You Fishing in the Right Pond?" },
  { id: "qrM1kIQ9KMw", title: "Choosing Inspiration Over Comparison" },
  { id: "6QR1GHa8nOk", title: "Referrals, Relationships, and Rocking the Ninja Nine" },
  { id: "NlHqXQjgXfM", title: "Going Through Five Stages of Change" },
  { id: "55L-7KiSGvA", title: "Matt and Garrett Host the Princeton Mortgage Panel" },
  { id: "q62YFad0nec", title: "Making Everyday Thanksgiving Day" },
  { id: "3W_QeKRoi8w", title: "Understanding Your Business Model to Determine Next Steps" },
  { id: "Klv6V5xAm58", title: "Getting Un-Stuck" },
  { id: "vMer6syr9YM", title: "Weekly Action Tip #216: Positive Emotional Energy" },
  { id: "MHIRCf5G1Xo", title: "Consistently Showing Up to Practice with Ninja Systems" },
  { id: "_zlOkMd-GFo", title: "Feedback or a Rating?" },
  { id: "Pb3Lkbb7GuA", title: "Tune Yourself for Optimal Performance this Holiday Season" },
  { id: "zLanQ-f9A5E", title: "Know Your Market Well" },
  { id: "lkuDSKYKz3I", title: "It's That Time of Year Again!" },
  { id: "lx-SJrJxeSM", title: "Letting Go of the False Narrative of Yesterday" },
  { id: "PlsneO8wNcg", title: "It's Episode 400 and We're Talking Parades!" },
  { id: "S-Ai8ptxhRA", title: "Show Up! Dress Up?" },
  { id: "PprswnVmwqk", title: "Reaping the Rewards of Open Houses" },
  { id: "lpQYTbv42kY", title: "The Deciding Factor for Success" },
  { id: "5Pi1-Ke9ymQ", title: "Ninja Weekly Action Tip #211: Plan Before There is Demand" },
  { id: "FY-b6uEiCxA", title: "The Benefits of Leading a Ninja Life with Rob Henderson" },
  { id: "xOOJlRJkpQM", title: "The Legend of the 'Normal Market'" },
  { id: "vWmF50xuRz8", title: "Ninja Weekly Action Tip #210: Know Your Market" },
  { id: "zvMPMNVLjUk", title: "Is the Sky Really Falling?" },
  { id: "EmuCqfEdeBE", title: "Data: Why it Matters" },
  { id: "pwNR7vwwM7E", title: "Failure to Launch" },
  { id: "QKAX8sNdmHw", title: "Pay Yourself First" },
  { id: "dh93dTKHFAc", title: "Weekly Action Tip #207: Habits 6, 7 and 8" },
  { id: "6RAMss_AGbo", title: "The Law of Precession" },
  { id: "OF11O2ILTbY", title: "Level Up with Custom Flow" },
  { id: "bCh7rJC6ug4", title: "Weekly Action Tip #206: Accept results and improve" },
  { id: "I1vl8n_I9Wk", title: "The Game Is Rigged in Your Favor" },
  { id: "wr5uWE2Gzqg", title: "Calming the Storm of Changing Inventory Levels" },
  { id: "Z2LOQWayRmc", title: "Weekly Action Tip #205: What you focus on expands!" },
  { id: "FTwYZnYdBXY", title: "Harnessing the Power of Data and Real Estate Reviews" },
  { id: "AJUi7N3aKpY", title: "Setting Your Sights on a Shared Vision" },
  { id: "ROAQok5inj0", title: "Weekly Action Tip #204: Start your 4th quarter off right" },
  { id: "-bhWXNzqhHc", title: "Getting Ready for the Rollercoaster" },
  { id: "GuQkRscKxjE", title: "Support, Camaraderie, and Lessons Learned at the Ninja Selling Guide Camp" },
  { id: "aaBCsm2ri8g", title: "Weekly Action Tip #203: Getting rid of old ways" },
  { id: "jq3Gj94fh0U", title: "Practicing Effective Internal Communication" },
  { id: "t5nB_AOmv-0", title: "The Power of a Clear Database" },
  { id: "hHFobAnxcQw", title: "Weekly Action Tip #202: Seek meaningful interaction" },
  { id: "gHpq6Ablb4Q", title: "Waving the Company Flag" },
  { id: "XQ96ztH_9ac", title: "The Dangers in Dating Your Interest Rate" },
  { id: "7o8LbFcGnOQ", title: "Weekly Action Tip #201: Time to be the proactive trusted advisor" },
  { id: "Q1RFyRMs2L4", title: "Going 'Off the Leash'" },
  { id: "dlbRtc7AYEQ", title: "Winning the Day with Agendas and the Ninja Nine" },
  { id: "DYP43CyU3e4", title: "Weekly Action Tip #200: Back to the basics" },
  { id: "J3618LQ8wk0", title: "Abundance Vs. Scarcity Mindset" },
  { id: "ZMwUiUZtFVI", title: "Postcards: Doing Them the Right Way" },
  { id: "_vtFOEKQa3U", title: "Weekly Action Tip #199: Amp the FLOW" },
  { id: "UKnMj9Hf8xo", title: "Have-To vs Get-To" },
  { id: "u5YVRqJBRKg", title: "Navigating False Flats to Keep Your Business Booming" },
  { id: "5UThbXfwQoA", title: "Weekly Action Tip #198: What do I send?" },
  { id: "CRWe1eirLYU", title: "The Perception of Power, Party, Peace, and Perfection Personality Profiles Personified and Placated" },
  { id: "FGlj1Okm6Gk", title: "Perfecting Real Estate Reviews for Today's Marketplace" },
  { id: "IflUfddIgNM", title: "Weekly Action Tip #196: Mindset, Skillset, Actions" },
  { id: "wITbrOHEWAg", title: "The Power of Creating Raving Fans" },
  { id: "94L8zwj82g4", title: "Never Stop Building Your Skill Set" },
  { id: "9EWeSocu09c", title: "Weekly Action Tip #196: 3 Circles of Life" },
  { id: "Wo4NXpO17Ok", title: "Navigating a Reactionary Society" },
  { id: "3l8jPWWKvBI", title: "Launching Listings—The Return" },
  { id: "fOMLGwibbuc", title: "Weekly Action Tip #195: Crack the Code on Your Datatbase" },
  { id: "Lv6EsNCr8_w", title: "Serving Up Success" },
  { id: "me6shlzYhb8", title: "Relationships, Service, and Building Social Proof" },
  { id: "NlCDzEa_qr8", title: "Weekly Action Tip #194: Why do we procrastinate?" },
  { id: "9-sZ9NQW7_M", title: "Let's Talk Pricing Sensitivity!" },
  { id: "iLcIS_VmoG0", title: "Networking The Right Way" },
  { id: "0xgmGSW7WEo", title: "Weekly Action Tip #193: Is now a good time to buy?" },
  { id: "2AR7iv-SlXQ", title: "Becoming a Track Star in the Real Estate Field" },
  { id: "z01fXSZuEDI", title: "Bringing Clarity to Price Drops" },
  { id: "s4h4KZeZst4", title: "Navigating the Current Market Scooch" },
  { id: "sJk9apcIfEo", title: "Call it a \"Shimmy\"" },
  { id: "8YxCBDQCaeo", title: "Weekly Action Tip #191: Winning an offer without bidding the highest price" },
  { id: "I1t3DK9zEII", title: "You're Not Losing Buyers!" },
  { id: "JI_hP4u-A00", title: "Permission Granted" },
  { id: "7NFhCPEk__I", title: "Weekly Action Tip #190: Making the complex simple" },
  { id: "8UCucqSdfKg", title: "What If?" },
  { id: "Bi2VNcDT7gw", title: "Is Time on Your Side?" },
  { id: "CtDxXhOB7E4", title: "Weekly Action Tip #189: Burnout and Ask a Ninja!" },
  { id: "jMqo0kTvMjc", title: "Walking the Ninja Selling Path with Larry Kendall - Part 2" },
  { id: "YFfeZ6irpxw", title: "Walking the Ninja Selling Path with Larry Kendall - Part 1" },
  { id: "c16wsJZjPeE", title: "Weekly Action Tip #188: Why use the 10 step buyer process?" },
  { id: "gSoSg1S-wQ4", title: "Be Careful What You Call an Investment" },
  { id: "CaTFlUFMp0I", title: "Setting Sellers' Expectations" },
  { id: "ywBblPVIpaQ", title: "Weekly Action Tip #187: Do you have faith?" },
  { id: "YdyYkYOSiYA", title: "Focusing on Abundance and Opportunity" },
  { id: "Rdmu49y-hLg", title: "Ninja Selling Beyond the Real Estate World with McKennan Hansen" },
  { id: "9pPMba3MX0k", title: "Weekly Action Tip #186: Lets quit what's working" },
  { id: "sTlLCbdIefc", title: "Situational Relationships" },
  { id: "yUW96eAZBmM", title: "Back Into the Wild" },
  { id: "zSOhoUGoODw", title: "Make This Your Gap Year" },
  { id: "sgIPqiVABII", title: "Weekly Action Tip #185: Lets show some caring" },
  { id: "dRqqX4QvEO8", title: "What You Focus on Expands" },
  { id: "lHI3tgB866o", title: "Weekly Action Tip #184: 5 questions to ask your buyers" },
  { id: "p15YL4syGZI", title: "Weekly Action Tip #183: Be the source of information" },
  { id: "0rJTBitYQ3Y", title: "Action Tip #182: Rating Hot & Warm List" },
  { id: "8cnG45MMH2E", title: "Action Tip #181: Are you going to be a player or a victim?" },
  { id: "apC97ejyWdo", title: "Action Tip #180: The Power of Auto-FLOW" },
  { id: "Od-_MP-Xhpw", title: "Action Tip #179: I have to get better" },
  { id: "Q3Lq0FWGJaA", title: "Action Tip #178: When Buyer's Regret Their Decision" },
  { id: "U0_aeGVXNJs", title: "Action Tip #177: The Zip Lock Bag" },
  { id: "nmm28QKgaHM", title: "Action Tip #176: Why Do Ninjas Exist?" },
  { id: "IZfsmHPm7W4", title: "Action Tip #175: The Dinner Playhouse Story" },
  { id: "ejC4rzQYoWA", title: "Action Tip #174: The Conversation is the Relationship" },
  { id: "7Q1hqszLJ4M", title: "Action Tip #173: Use this trick when making a phone call" },
  { id: "xWIZGL5Bib8", title: "Action Tip #172: How to get off the \"treadmill\"" },
  { id: "PcyEV1ZKeho", title: "Action Tip #171: Focus on this Skillset" },
  { id: "2bfFs1n5kZ0", title: "Action Tip #170: 10 Step Formula to a Successful 2022" },
  { id: "FGOcbj_n-EU", title: "Best of Weekly Action Tips #8: Excellence is a Habit" },
  { id: "BzJVYKK9uW8", title: "Best of Weekly Action Tips #7: Power of Process" },
  { id: "xgIC066Yk0s", title: "Best of Weekly Action Tips #6: Daruma Doll" },
  { id: "faN5E1m5Ajs", title: "Best of Weekly Action Tips #5: Word of the Year" },
  { id: "8b-KmXHYijA", title: "Best of Weekly Action Tips #4: Solve for Price" },
  { id: "_pTKAFHUvl0", title: "Best of Weekly Action Tips #3: Blue Footed Booby" },
  { id: "_9s1laeiYGo", title: "Best of Weekly Action Tips #2: Best Lead Generation Activity" },
  { id: "fHjA3deWjS4", title: "Best of Weekly Action Tips #1: Never Break the Chain" },
  { id: "gCDBVbwsQ5g", title: "Action Tip #169: What is your Identity?" },
  { id: "heZ3S__Gjwg", title: "Action Tip #168: It's Business Planning Season!" },
  { id: "OFEWuUtFDBQ", title: "Action Tip #167: \"Adding\" to our Business" },
  { id: "ja8Iu1xc2_4", title: "Action Tip #148: Why follow a process?" },
  { id: "jihcOzq_nbg", title: "Action Tip#147: Being Grateful" },
  { id: "Z8iukrEDVLg", title: "Action Tip #146: Fun Facts" },
  { id: "QPda-gDmUOg", title: "Action Tip #145: The Hour of Power" },
  { id: "dELj50aW0Gg", title: "Action Tip #144: How are you time blocking?" },
  { id: "tpCSDUsbTsY", title: "Action Tip #142: How do we help our people?" },
  { id: "ZUPmI4w3G7E", title: "Be the source of information" },
  { id: "UATu-BrYbu4", title: "How to stay on top of your Ninja Nine" },
  { id: "0El6GlgTG_4", title: "Action Tip #139: Why do customer service calls?" },
  { id: "A2kYkFUAYd0", title: "What is your resistance" },
  { id: "tdm5JXXEjzU", title: "What is your Ninja competence level?" },
  { id: "8C5B5JjXcn4", title: "Will your listing make the cut?" },
  { id: "SdsscMPiShI", title: "Solve for Price" },
  { id: "ohOsUUZhIcY", title: "Ninja Morning Routine" },
  { id: "Mau3dti1c20", title: "What do you really want?" },
  { id: "9zmn7PbS6Zc", title: "Action Tip #118 - The Power of Process" },
  { id: "35F5xj3DaiU", title: "Action Tip #117 - It's Business Planning Month" },
  { id: "C5DRuM0xV8U", title: "Action Tip #116 - Your 50 Live Interviews" },
  { id: "HtLnbYcSsA0", title: "Number 5 in the 5 rules of Ninja selling is: Don't get attached to the outcome" },
  { id: "MOZ4YY-rxGU", title: "Gratitudes" },
  { id: "HXf2015FQF8", title: "Number 3 in the 5 rules of Ninja selling is: Do what you say and keep your commitments." },
  { id: "Nhu2NRNc7_k", title: "Finding a new comfort level" },
  { id: "QoxskHww5kE", title: "Physical distancing not social" },
  { id: "U3PG70KesA4", title: "DO YOUR HOT LIST" },
  { id: "hnU70mOV6Wk", title: "3 tips heading into fall" },
  { id: "DNrXT_k3Wvk", title: "Success Habit #6" },
  { id: "uWr7HMdqaos", title: "Success Habit #3" },
  { id: "mBjsEmhoURI", title: "Do you have a process?" },
  { id: "HjiypH-WT7I", title: "Scorecards" },
  { id: "87o9VOAnzeg", title: "Non-negotiables" },
  { id: "w5bGhLe5shI", title: "The Realtor's Prayer Episode #110" },
  { id: "0ZdiUYcAlI0", title: "How's Your Accountability? Episode #109" },
  { id: "c14lpPWXhGo", title: "The Infinite Game. Episode #108" },
  { id: "ZTjelvpR_Nc", title: "This is a set up! Episode #107" },
  { id: "AZ_73Sq-fJ8", title: "What is Ninja Selling" },
  { id: "rg0Sj2IETn4", title: "Atomic Habits. Episode #106" },
  { id: "Oab0zgY2QQ8", title: "Ninja Selling Testimonials" },
  { id: "docUDABvL5U", title: "Welcome to the Ninja Path" },
  { id: "S3nw15VL1Hs", title: "Bring Your A Game. Episode #104" },
  { id: "FVrYupJdnEE", title: "Ninja Weekly Routine Part 3" },
  { id: "ecAJiCnEGNk", title: "Ninja Weekly Routine Part 2, continued from March 6!" },
  { id: "y0gfGCl8-zQ", title: "Ninja Selling Results" },
  { id: "LPbaGoudkuU", title: "Exciting News!" },
  { id: "mdLUduzu-xU", title: "Give Yourself a Grade" },
  { id: "aExFl5hYEP0", title: "Am I enough" },
  { id: "Z9oemKxPkZI", title: "Fix your phone and a real estate update" },
  { id: "wUi7d0PlYgU", title: "The One Thing" },
  { id: "SQplLwWwh7k", title: "All of our people are wondering what is going on with the values in their neighborhood!" },
  { id: "bkOPc6FqecY", title: "The question they are all asking." },
  { id: "eyt9klIATyM", title: "Larry Kendall's COVID-19 Response" },
  { id: "mKAFCtXgfZA", title: "Plant seeds now!" },
  { id: "GjxTaOTgbVw", title: "More Ninjas Ideas around COVID-19." },
  { id: "rbrx14Qoz7Y", title: "Let's stay valuable as Ninjas!" },
  { id: "zr2wR0vWxNA", title: "Ninjas and COVID-19" },
  { id: "nWYXgyrNupE", title: "Ninja Weekly Routine Broken Down by Don Tennessen" },
  { id: "0bIpMArb9dc", title: "I haven't talked to them in 2 years!" },
  { id: "kgcCTVvD-c8", title: "Revisit your \"Word of the Year\"" },
  { id: "Piz0uLcTs2I", title: "Do you remember a key to increasing your income per hour?" },
  { id: "dUboaB3E7TU", title: "Every day we have a choice of how we \"show up\"." },
  { id: "u2UoJvra0Us", title: "Simon Sinek says...Start with Why" },
  { id: "YTgF67FCo5E", title: "Your \"One Day\"" },
  { id: "Ypt6UiaRyA4", title: "New Year Habits and how they influence your year as a Ninja." },
  { id: "C0kmujH9uUg", title: "Create a Real Estate Review" },
  { id: "0yQI3bcSrBo", title: "The best lead generation activity ever!" },
  { id: "ge6ZluujyzI", title: "The steps in MLS to prepare a RER" },
  { id: "v105U9YzpMA", title: "Real Estate Reviews Revisited." },
  { id: "l5ntvymCYZ4", title: "The start of a fantastic 2020!" },
  { id: "OLNxKfZhqlA", title: "This is the last Ninja Nation Action tip for 2019!" },
  { id: "7dBLbAGQNKE", title: "Word of the year" },
  { id: "sEBAdnYPY2E", title: "It's Monday the 23rd of December!!!" },
  { id: "7gCTXF460ws", title: "Work Life Harmony is the goal" },
  { id: "La7gKNmdCbY", title: "This is a great way to stay on your Ninja Path during the Holidays." },
  { id: "rd7Fwa2FLjI", title: "Use the Five Magic Questions this Holiday Season!" },
  { id: "i88Zqii-dqU", title: "What a great way to end your year!" },
  { id: "GtCcrT8AqYg", title: "Happy Thanksgiving from all of us at Ninja Selling" },
  { id: "Wwi42Dr1q9A", title: "What is the Real Reason for a Business Plan?" },
  { id: "SGVADG05G5k", title: "Week 1 post Installation" },
  { id: "n-r1yxw4qPM", title: "Do your Pre Flight Checklist" },
  { id: "KHBhJU02Boc", title: "Ninja Business Planning week 3" },
  { id: "EjU4yMVhlu8", title: "Get clear on what your Financial Goal for 2020, the Ninja Way." },
  { id: "gAP30uJrZWw", title: "Life List creation" },
  { id: "py6pKEst_Hc", title: "Ninja Business Plan Step One.  Build your Life List...your \"Why\"." },
  { id: "gcR4KkChDlU", title: "For Ninjas creating Fabled Service is everything." },
  { id: "640TpBq_seA", title: "How distractions keep us from making decisions" },
  { id: "Wr6SfcxYftA", title: "In a slump?" }
]

export const ninjaConcepts: NinjaConcept[] = [
  {
    id: "four-cornerstones",
    name: "The Four Cornerstones",
    description: "The foundation of Ninja Selling rests on four cornerstones that guide everything a Ninja does: Personal Mastery, Stop Selling Start Solving, Ninja Business Strategy, and Connect & Communicate.",
    principles: [
      "Personal Mastery: Develop yourself first - mindset, habits, and continuous growth",
      "Stop Selling, Start Solving: Focus on solving people's problems, not pushing products",
      "Ninja Business Strategy: Build a referral-based business with a structured plan",
      "Connect & Communicate: Build authentic relationships through genuine connection"
    ],
    actionItems: [
      "Start each day with gratitude and affirmations",
      "In every conversation, ask 'How can I help?' instead of 'How can I sell?'",
      "Create your annual business plan with clear financial goals",
      "Practice the FORD method in every interaction"
    ]
  },
  {
    id: "ninja-nine",
    name: "The Ninja Nine",
    description: "Nine daily and weekly disciplines that form the backbone of a successful Ninja practice. These habits, when done consistently, create a compounding effect that builds your business organically.",
    principles: [
      "1. Gratitude & Appreciation - Start each day grateful",
      "2. Affirmations & Visualization - See your success before it happens",
      "3. Review your goals & schedule daily",
      "4. Write 2 personal notes per day",
      "5. Make your live interviews (phone calls to your database)",
      "6. Track your numbers on the Ninja Scorecard",
      "7. Attend your Ninja sales meeting weekly",
      "8. Prepare and practice your skills",
      "9. Invest in personal development (E-Time)"
    ],
    actionItems: [
      "Set up a morning routine that includes gratitude and affirmations",
      "Keep personal note cards and stamps at your desk",
      "Schedule 2 hours of phone time per week for live interviews",
      "Track your activities on the Ninja Scorecard daily",
      "Dedicate at least 2 hours per week to education and training"
    ]
  },
  {
    id: "ford-method",
    name: "FORD Method",
    description: "FORD stands for Family, Occupation, Recreation, and Dreams. It's a framework for having meaningful conversations that build deep, authentic relationships with your contacts.",
    principles: [
      "Family: Ask about their family, kids, pets, and loved ones",
      "Occupation: Learn about their work, career goals, and professional life",
      "Recreation: Discover their hobbies, interests, and how they spend free time",
      "Dreams: Uncover their aspirations, bucket list items, and future goals",
      "Listen more than you talk - the goal is to learn about THEM"
    ],
    actionItems: [
      "Record FORD notes in your CRM after every meaningful conversation",
      "Use FORD topics to start conversations during pop-bys",
      "Reference previous FORD details in follow-up conversations",
      "Ask about dreams - this is where real estate opportunities emerge",
      "Practice active listening: put down your phone and be present"
    ]
  },
  {
    id: "flow-system",
    name: "Flow & Auto-Flow",
    description: "Flow is Ninja Selling's systematic approach to maintaining consistent contact with your database. Auto-Flow automates touchpoints so no one falls through the cracks, while personal Flow adds the human touch.",
    principles: [
      "Auto-Flow: Automated monthly value-add touches (market updates, newsletters, etc.)",
      "Personal Flow: Intentional calls, notes, and pop-bys on a scheduled basis",
      "Customer Service Calls: Regular check-ins with past clients",
      "The goal is staying top-of-mind without being pushy",
      "Consistency beats intensity - small regular touches outperform occasional big gestures"
    ],
    actionItems: [
      "Set up a monthly auto-flow email/newsletter with market insights",
      "Schedule customer service calls for all past clients quarterly",
      "Plan quarterly pop-bys for your top 100 contacts",
      "Use your CRM to track last contact dates and set reminders",
      "Create a flow calendar that maps out the entire year"
    ]
  },
  {
    id: "real-estate-reviews",
    name: "Real Estate Reviews",
    description: "Annual property reviews position you as a trusted advisor rather than a salesperson. By helping homeowners understand their property value, equity, and market position, you create natural opportunities for business.",
    principles: [
      "Provide value by analyzing the homeowner's property value and equity growth",
      "Review insurance coverage to ensure adequate protection",
      "Discuss neighborhood market trends and recent sales",
      "Position yourself as their lifelong real estate advisor",
      "Reviews naturally surface listing, buying, and referral opportunities"
    ],
    actionItems: [
      "Schedule annual reviews for all homeowner contacts",
      "Prepare a professional property analysis report before each review",
      "Host quarterly market update events for groups of contacts",
      "Follow up within 48 hours with a summary and any action items",
      "Ask for referrals naturally: 'Who else might benefit from a review like this?'"
    ]
  },
  {
    id: "buyer-seller-process",
    name: "The Ninja Buyer & Seller Process",
    description: "Structured step-by-step processes for guiding buyers and sellers through their real estate journey with professionalism, care, and a consultative approach.",
    principles: [
      "10-Step Buyer Process: From initial consultation to closing and beyond",
      "Buyer consultation before showing homes - understand their needs first",
      "Strategic pricing for sellers - solve for price, don't just list high",
      "Pre-listing packet and listing consultation process",
      "Post-closing follow-up and transition to long-term relationship"
    ],
    actionItems: [
      "Always start with a buyer consultation before showing any homes",
      "Use the pre-listing packet to set expectations and demonstrate value",
      "Practice the pricing conversation using Ninja scripts",
      "Create a closing gift and follow-up system",
      "Add every closed client to your top 100 database"
    ]
  },
  {
    id: "pie-time",
    name: "PIE Time Management",
    description: "The PIE framework divides your work time into three categories to ensure balanced effort across all aspects of your business: Proactive time, Income time, and Education time.",
    principles: [
      "P-Time (Proactive): Database work, pop-bys, calls, notes - building relationships",
      "I-Time (Income): Showings, listings, negotiations, closings - generating revenue",
      "E-Time (Education): Training, learning, personal development - growing skills",
      "The 20-hour work week: Work smarter, not harder",
      "Protect your P-Time - it's the engine that drives future business"
    ],
    actionItems: [
      "Block P-Time on your calendar first, before anything else",
      "Aim for at least 10 hours of P-Time per week",
      "Track your PIE hours weekly in the Weekly Planning section",
      "Don't let I-Time crowd out P-Time during busy periods",
      "Schedule at least 2 hours of E-Time weekly for growth"
    ]
  },
  {
    id: "handwritten-notes",
    name: "Handwritten Notes & Personal Touches",
    description: "In a digital world, handwritten notes create an outsized impact. They show you care enough to take the time, and they stand out in a sea of emails and texts.",
    principles: [
      "Write at least 2 personal notes per day (part of the Ninja Nine)",
      "Notes should be personal, not business-focused",
      "Reference specific details from your FORD conversations",
      "Handwritten notes have a 99% open rate vs. email's ~20%",
      "The goal is making people feel valued, not generating leads"
    ],
    actionItems: [
      "Stock up on quality note cards and stamps",
      "Set a daily reminder to write your 2 notes",
      "After every meaningful conversation, send a follow-up note",
      "Celebrate milestones: birthdays, anniversaries, achievements",
      "Keep a 'notes sent' tracker on your Ninja Scorecard"
    ]
  }
]
