export interface Video {
  id: string
  title: string
}

export interface Category {
  id: string
  name: string
  description: string
  videoCount: number
  icon: string
  gradient: string
  featuredVideos: Video[]
}

export interface NinjaConcept {
  id: string
  name: string
  description: string
  deepDive: string
  principles: string[]
  actionItems: string[]
}

export interface GettingStartedStep {
  step: number
  title: string
  description: string
  timeframe: string
  tasks: string[]
}

export const gettingStartedSteps: GettingStartedStep[] = [
  {
    step: 1,
    title: "Commit to the Mindset Shift",
    description: "Before any tactics, Ninja Selling requires a fundamental shift: stop thinking like a salesperson, start thinking like a problem solver. You are not selling houses — you are helping people make the best decisions for their lives. Read (or re-read) Larry Kendall's book 'Ninja Selling: Subtle Skills. Big Results.' to internalize the philosophy.",
    timeframe: "Week 1",
    tasks: [
      "Read 'Ninja Selling' by Larry Kendall cover to cover",
      "Write down your personal 'why' — why are you in real estate beyond money?",
      "Create your Life List: 100 things you want to be, do, and have in your lifetime",
      "Set a 'Word of the Year' that will guide your focus and intentions"
    ]
  },
  {
    step: 2,
    title: "Build Your Morning Routine",
    description: "Your morning routine is the engine of the Ninja system. The first three of the Ninja Nine happen before you start 'work.' A consistent morning routine programs your subconscious mind for success and ensures you start each day intentionally rather than reactively.",
    timeframe: "Week 1-2",
    tasks: [
      "Set a consistent wake-up time and protect the first 60-90 minutes of your day",
      "Start a gratitude journal — write 3 things you're grateful for each morning",
      "Write and read your affirmations daily (present tense, positive statements about your goals)",
      "Spend 5-10 minutes visualizing your ideal day and the goals you're working toward",
      "Review your schedule, goals, and priorities before checking email or social media"
    ]
  },
  {
    step: 3,
    title: "Organize Your Database",
    description: "Your database is your most valuable business asset. Ninja Selling is a relationship-based system, so you need to know exactly who is in your world, how to reach them, and how to provide them value. A disorganized database means missed opportunities every single day.",
    timeframe: "Week 2-3",
    tasks: [
      "Choose a CRM system (or clean up your existing one) — Top Producer, Follow Up Boss, KvCORE, etc.",
      "Import all contacts: past clients, sphere of influence, friends, family, neighbors, community connections",
      "Categorize contacts into A (close relationships), B (acquaintances), and C (met once / loose connections)",
      "Add FORD notes (Family, Occupation, Recreation, Dreams) for everyone you know well",
      "Identify your Hot List: people likely to buy, sell, or refer within the next 12 months",
      "Set a goal to grow your database by 2-5 new contacts per week"
    ]
  },
  {
    step: 4,
    title: "Launch Your Ninja Nine Habits",
    description: "The Ninja Nine are non-negotiable daily and weekly disciplines. Don't try to be perfect — just start. Consistency compounds over time. Most agents see meaningful results within 60-90 days of consistent Ninja Nine practice. Track everything on your Ninja Scorecard.",
    timeframe: "Week 3-4",
    tasks: [
      "Order personal note cards and stamps — write 2 handwritten notes per day",
      "Schedule your weekly phone/call time — aim for 50 live conversations per week",
      "Set up your Ninja Scorecard (spreadsheet or printed) and track daily activities",
      "Block 'P-Time' (Proactive Time) on your calendar — this is when you do database work, calls, and notes",
      "Start your weekly planning session: every Sunday or Monday, plan your Ninja Nine for the week"
    ]
  },
  {
    step: 5,
    title: "Set Up Your Flow System",
    description: "Flow is how you stay in touch with your database consistently, so when someone is ready to buy, sell, or refer, you are the first person they think of. Auto-Flow handles the baseline touches automatically; Personal Flow adds the human element that builds real trust.",
    timeframe: "Week 4-6",
    tasks: [
      "Set up Auto-Flow: a monthly email or newsletter with market updates, tips, or community news",
      "Create a quarterly pop-by plan for your top contacts (small gifts + face time)",
      "Schedule annual Customer Service Calls for all past clients",
      "Map out your 12-month flow calendar: which touches happen each month?",
      "Start offering free Annual Real Estate Reviews to homeowners in your database"
    ]
  },
  {
    step: 6,
    title: "Master Your Conversations",
    description: "Ninja Selling is not about scripts — it's about genuine, curious conversations that naturally uncover opportunities. Learn the FORD method, practice the Ninja Interview (asking great questions), and get comfortable with the pricing and consultation conversations.",
    timeframe: "Week 6-8",
    tasks: [
      "Practice the FORD method in every conversation — ask about Family, Occupation, Recreation, and Dreams",
      "Role-play the Buyer Consultation with a partner until it feels natural",
      "Role-play the Seller Consultation and pricing conversation",
      "Learn the '16 Magic Questions' for open houses and buyer interactions",
      "Practice the 'Hot Button' close: connecting solutions to what people told you they care about"
    ]
  },
  {
    step: 7,
    title: "Create Your Business Plan",
    description: "Now that you have the habits and systems in place, build a concrete business plan that connects your life goals to your daily activities. Work backwards from your income goal to determine exactly how many contacts, appointments, and closings you need.",
    timeframe: "Week 8-10",
    tasks: [
      "Define your annual income goal and calculate your 'number' (closings needed)",
      "Work backwards: closings needed → appointments needed → contacts needed per week",
      "Set quarterly milestones so you can track progress and adjust",
      "Identify your target market and geographic farm area",
      "Review your plan monthly and adjust based on actual results vs. projections"
    ]
  },
  {
    step: 8,
    title: "Join & Engage with the Ninja Community",
    description: "Ninja Selling works best when you're plugged into a community of like-minded agents. Accountability, shared learning, and consistent reinforcement keep you on track when motivation dips. The Ninja Installation is the ideal starting point, but there are many ways to stay connected.",
    timeframe: "Ongoing",
    tasks: [
      "Attend a Ninja Selling Installation (the official 2-day immersive training)",
      "Join or form a Ninja Mastermind group for weekly accountability",
      "Attend your office's Ninja meetings or start one if there isn't one",
      "Subscribe to the Ninja Selling YouTube channel and watch 1-2 videos per week",
      "Re-read sections of the book quarterly to reinforce concepts as your business grows"
    ]
  }
]

export const categories: Category[] = [
  { id: "personal-mastery-and-mindset", name: "Personal Mastery & Mindset", description: "Developing a growth mindset, personal mastery, self-improvement, confidence, abundance vs. scarcity thinking, energy management, overcoming fear and limiting beliefs, and the mental game of success.", videoCount: 134, icon: "Brain", gradient: "from-purple-500 to-indigo-600", featuredVideos: [{ id: "IS1470U8xiM", title: "What is Personal Mastery in Ninja Selling?" }, { id: "LtF7nlt2lYk", title: "The Level Up Moment: Leading with Mindset, Skillset, and Action" }, { id: "VFJZeD6iWU8", title: "Building Unshakable Confidence for Real Estate Agents" }, { id: "CRWe1eirLYU", title: "The Perception of Power, Party, Peace, and Perfection Personality Profiles" }, { id: "4lwMtg1zP18", title: "Personal Mastery: The First Cornerstone of Ninja" }] },
  { id: "ninja-selling-system-foundations", name: "Ninja Selling System Foundations", description: "Core introductions to the Ninja Selling system, its philosophy, the four cornerstones, installations, rules, foundational concepts, and the Ninja path.", videoCount: 40, icon: "BookOpen", gradient: "from-teal-500 to-cyan-600", featuredVideos: [{ id: "2WKDpsTEOTY", title: "Ninja In A Nutshell - An Overview of the Ninja Selling System" }, { id: "WC_nezGrWJ4", title: "Live From The Ninja Installation: Trust the Process" }, { id: "LCel0MB8Bw0", title: "Stop Selling. Start Solving. The Second Cornerstone" }, { id: "HXf2015FQF8", title: "Rule #3: Do what you say and keep your commitments" }, { id: "HtLnbYcSsA0", title: "Rule #5: Don't get attached to the outcome" }] },
  { id: "business-planning-and-goal-setting", name: "Business Planning & Goal Setting", description: "Annual and quarterly business planning, goal setting, financial targets, life lists, word of the year, and strategic planning frameworks for building a successful real estate career.", videoCount: 35, icon: "Target", gradient: "from-emerald-500 to-green-600", featuredVideos: [{ id: "py6pKEst_Hc", title: "Ninja Business Plan Step One: Build your Life List" }, { id: "3W_QeKRoi8w", title: "Understanding Your Business Model to Determine Next Steps" }, { id: "-QLdV8uPtZE", title: "How to Finish Strong and Set Up for Success" }, { id: "tp3-f7IfZNI", title: "Finish Strong by Reviewing What Worked (and What Didn't)" }, { id: "2bfFs1n5kZ0", title: "10 Step Formula to a Successful Year" }] },
  { id: "ninja-nine-and-daily-habits", name: "Ninja Nine & Daily Habits", description: "The nine daily and weekly habits that form the foundation of the Ninja Selling system, including gratitude, affirmations, morning routines, scorecards, the Ninja Planner, time blocking, and tracking progress.", videoCount: 32, icon: "ListChecks", gradient: "from-blue-500 to-indigo-600", featuredVideos: [{ id: "FGOcbj_n-EU", title: "Best of Weekly Action Tips: Excellence is a Habit" }, { id: "fHjA3deWjS4", title: "Best of Weekly Action Tips: Never Break the Chain" }, { id: "1lxD6ibUcG0", title: "Mastering the Ninja Planner with Creator Eric Hardy" }, { id: "UedLGJTp9KU", title: "Want More Closings? Master Your PIE Time" }, { id: "JAgIsaRpZ5c", title: "The Ninja Scorecard - Your Plan for Consistency" }] },
  { id: "market-updates-and-economic-insights", name: "Market Updates & Economic Insights", description: "Analysis of current real estate market conditions, interest rates, housing trends, economic indicators, mortgage insights, inventory levels, and navigating market shifts.", videoCount: 29, icon: "TrendingUp", gradient: "from-orange-500 to-red-600", featuredVideos: [{ id: "MO_CPEilpfw", title: "Consistent Volume in an Inconsistent Market Using Consistent Routines" }, { id: "SQplLwWwh7k", title: "What is going on with values in their neighborhood?" }, { id: "qKRDyrp5aoc", title: "Insights and Opportunities in Today's Real Estate Market" }, { id: "APK1mycdSM0", title: "This Economic Indicator Could Be Your Next Opportunity" }, { id: "iRBxDL_r10s", title: "Understanding and Outperforming the Market" }] },
  { id: "general-ninja-wisdom-and-motivation", name: "General Ninja Wisdom & Motivation", description: "Broader motivational content, general business wisdom, seasonal messages, and miscellaneous tips that reinforce the Ninja mindset and approach to business and life.", videoCount: 29, icon: "Sparkles", gradient: "from-yellow-500 to-orange-600", featuredVideos: [{ id: "D5A55uPxzTY", title: "The Opportunities in Change - Larry Kendall, Jack Miller, Mike Staver" }, { id: "u5YVRqJBRKg", title: "Navigating False Flats to Keep Your Business Booming" }, { id: "5Pi1-Ke9ymQ", title: "Plan Before There is Demand" }, { id: "Wo4NXpO17Ok", title: "Navigating a Reactionary Society" }, { id: "YmqayfSZK0Q", title: "The Stuff Trap" }] },
  { id: "flow-and-auto-flow-systems", name: "Flow & Auto-Flow Systems", description: "Ninja Selling's systematic approach to staying in touch with your database through automated and intentional touchpoints, customer service calls, flow schedules, and systematic follow-up.", videoCount: 22, icon: "Repeat", gradient: "from-cyan-500 to-blue-600", featuredVideos: [{ id: "r1QbMt3Xjto", title: "Auto-Flow 101: Why Flow Fixes Everything" }, { id: "NYIhCLe-ZFo", title: "Why 'Flow Fixes Everything' in Real Estate" }, { id: "fge6q4Qbgj8", title: "Frictionless Referrals: Introducing Referral Flow" }, { id: "9IrI5eCIGNg", title: "The Secret to Guilt-Free Client Follow Up" }, { id: "n-_1Xu5ZUpY", title: "Rebuilding on Purpose Through Flow" }] },
  { id: "referrals-and-relationship-building", name: "Referrals & Relationship Building", description: "Building a referral-based business through genuine relationships, becoming referable, creating raving fans, and generating business through authentic connection rather than hard selling.", videoCount: 21, icon: "Heart", gradient: "from-rose-500 to-pink-600", featuredVideos: [{ id: "WxPQzM6iqTU", title: "How To Generate Referrals Without Asking" }, { id: "yu_7yzbLHfU", title: "How To Be Consistently Magnetic" }, { id: "wITbrOHEWAg", title: "The Power of Creating Raving Fans" }, { id: "49PhQ8nwzjM", title: "This Simple Action Creates Referrals (and it's Not Selling)" }, { id: "me6shlzYhb8", title: "Relationships, Service, and Building Social Proof" }] },
  { id: "ninja-coaching-spotlights", name: "Ninja Coaching Spotlights", description: "Spotlight interviews with Ninja coaches sharing insights, strategies, and coaching success stories that illustrate how Ninja principles work in real-world coaching scenarios.", videoCount: 18, icon: "Mic", gradient: "from-indigo-500 to-purple-600", featuredVideos: [{ id: "TUSgP6pL-Ho", title: "Ninja Coaches: Why Agents Use Them To Win" }, { id: "ftqxEQvV0M0", title: "Coaching Spotlight with Christine Moore and Tracy Peterson-Nienaber" }, { id: "-GvT0jBhB8c", title: "Coaching Spotlight with Patty Schmitz-Thursam and Natalie Davis" }, { id: "8-B8RO455ME", title: "Coaching Spotlight on Peggy Shanklin and Shelly Culbertson" }, { id: "NTsUTd6p0Ok", title: "Coaching Spotlight with Christina O'Neal and Mark Johnson" }] },
  { id: "time-management-and-productivity", name: "Time Management & Productivity", description: "Time blocking, calendar management, productivity strategies, work-life harmony, the PIE framework (Proactive, Income, Education time), and creating efficient daily routines.", videoCount: 17, icon: "Clock", gradient: "from-emerald-500 to-teal-600", featuredVideos: [{ id: "gyTv6IyLlFY", title: "Why Haven't I Been Doing This the Entire Time?" }, { id: "O8ukIUoinhw", title: "Choosing the Right Vehicle on the Road to Life-Work Harmony" }, { id: "7o8LbFcGnOQ", title: "Time to be the proactive trusted advisor" }, { id: "xWIZGL5Bib8", title: "How to get off the 'treadmill'" }, { id: "Piz0uLcTs2I", title: "A key to increasing your income per hour" }] },
  { id: "consistency-accountability-and-process", name: "Consistency, Accountability & Process", description: "The importance of daily consistency, building accountability structures, following proven processes, and the compounding effect of showing up with discipline every day.", videoCount: 17, icon: "RefreshCw", gradient: "from-slate-500 to-gray-600", featuredVideos: [{ id: "BzJVYKK9uW8", title: "Power of Process" }, { id: "ja8Iu1xc2_4", title: "Why follow a process?" }, { id: "MHIRCf5G1Xo", title: "Consistently Showing Up to Practice with Ninja Systems" }, { id: "2GWGk4kgKac", title: "Consistency, Commitment, and Success by the Numbers" }, { id: "9zmn7PbS6Zc", title: "The Power of Process" }] },
  { id: "seller-process-and-listing-strategies", name: "Seller Process & Listing Strategies", description: "Listing consultations, strategic pricing, pre-listing packets, managing seller expectations, navigating pricing conversations, and the step-by-step Ninja seller process.", videoCount: 15, icon: "Home", gradient: "from-amber-500 to-orange-600", featuredVideos: [{ id: "8KlbnMzRmRQ", title: "Navigating Seller Risk: A Modern Approach to Pricing" }, { id: "bYnWVpkeZHs", title: "The Keys to Successful Listing Consultations" }, { id: "ly9r2hU_iy0", title: "Negotiating Sellers' Specific Financial Expectations" }, { id: "awpCk4zyd3g", title: "The Power of Strategic Pricing" }, { id: "8b-KmXHYijA", title: "Solve for Price" }] },
  { id: "conversations-questions-and-ford", name: "Conversations, Questions & FORD", description: "The FORD method (Family, Occupation, Recreation, Dreams), asking powerful questions, deep listening, conversation starters, and the art of meaningful dialogue that builds relationships.", videoCount: 15, icon: "MessageCircle", gradient: "from-sky-500 to-blue-600", featuredVideos: [{ id: "NyGbnpFRy24", title: "The Art of the Question: Next-Level Conversations" }, { id: "tgFqhzIMZTU", title: "Holiday Conversations That Actually Matter" }, { id: "Y8Vss_uaNl8", title: "How to Turn a Dream into a Reality" }, { id: "TVSjxqel9Ns", title: "Why Bother Asking? (You Should!)" }, { id: "YXjDBlk1mVc", title: "Dream It. Plan It. Do It. Celebrate It." }] },
  { id: "buyer-process-and-strategies", name: "Buyer Process & Strategies", description: "The Ninja buyer process, buyer consultations, creating buyers, working with offers, and strategies for guiding buyers through their home purchase journey.", videoCount: 14, icon: "ShoppingCart", gradient: "from-lime-500 to-green-600", featuredVideos: [{ id: "c16wsJZjPeE", title: "Why use the 10 step buyer process?" }, { id: "TRHFbYodxvA", title: "The Pivot from Buying Leads to Building Relationships" }, { id: "8YxCBDQCaeo", title: "Winning an offer without bidding the highest price" }, { id: "L1wX3OrOjsY", title: "Unlocking Homeownership: It's Not Just About Income" }, { id: "4TBBZBzr2rA", title: "Opening Up Inventory with Contingent Offers" }] },
  { id: "database-and-contact-management", name: "Database & Contact Management", description: "Building, managing, rating, and leveraging your contact database and CRM systems, hot/warm/cold list strategies, and the 50 live interviews concept.", videoCount: 13, icon: "Database", gradient: "from-violet-500 to-purple-600", featuredVideos: [{ id: "JD17rt5YqfE", title: "Unlocking the Power of Your Hot and Warm List" }, { id: "INs9lxeeLrg", title: "Building Your Warm List" }, { id: "fOMLGwibbuc", title: "Crack the Code on Your Database" }, { id: "xCMEE8zORRk", title: "What is the best CRM?" }, { id: "C5DRuM0xV8U", title: "Your 50 Live Interviews" }] },
  { id: "notes-calls-and-outreach-methods", name: "Notes, Calls & Outreach Methods", description: "Phone call techniques, handwritten notes, electronic notes, communication strategies, text messaging best practices, and multi-channel outreach approaches.", videoCount: 13, icon: "Phone", gradient: "from-pink-500 to-rose-600", featuredVideos: [{ id: "cA79L9ActJM", title: "The Power of Handwritten Notes in a Digital World" }, { id: "ybOd55CEfLw", title: "Why You're Hesitating to Reach Out" }, { id: "k4sTso2LEBM", title: "Unearthing the Beet and Potatoes of Successful Phone Calls" }, { id: "MtjcfMhP4mQ", title: "Phone Calls, Texts, and Effective Communication" }, { id: "7Q1hqszLJ4M", title: "Use this trick when making a phone call" }] },
  { id: "team-building-and-leadership", name: "Team Building & Leadership", description: "Building and leading real estate teams, developing company culture, hiring and mentoring, team structures, and leadership development for real estate professionals.", videoCount: 13, icon: "Users", gradient: "from-fuchsia-500 to-purple-600", featuredVideos: [{ id: "O-FuU1mRUbc", title: "How to Build a Team That Actually Works" }, { id: "kTDF9KQJjKw", title: "Building a Thriving Team and Business with John Newman" }, { id: "GVD4Kr0x3j4", title: "How to Build a Ninja Company: A Blueprint from Jenny Usaj" }, { id: "guptRmiGo0I", title: "How to Effectively Hand Off Your Real Estate Business" }, { id: "26fFCYtAu9s", title: "The Team Leader Blueprint" }] },
  { id: "success-stories-and-case-studies", name: "Success Stories & Case Studies", description: "Real-world success stories from Ninja practitioners, impressive production numbers, transformational journeys, and case studies that demonstrate the Ninja Selling system in action.", videoCount: 10, icon: "Trophy", gradient: "from-yellow-500 to-amber-600", featuredVideos: [{ id: "LoRzDXnzgDI", title: "How a Rookie Did $28M in His First Year" }, { id: "enPY66udOro", title: "From $8,000 a Year to $308,000 a Year in Five Years" }, { id: "3iLTcuHEQ-Y", title: "From Classroom to Closing: A College Course Launched a Ninja Career" }, { id: "9JWJz5pf0Rk", title: "The Ninja Couple: From Military Precision to Real Estate Success" }, { id: "tUYd92RyZ_E", title: "The $1 Million Secret with Amy Balewicz" }] },
  { id: "prospecting-and-lead-generation", name: "Prospecting & Lead Generation", description: "Lead generation strategies, networking techniques, building your sphere of influence, community involvement, and organic prospecting that aligns with the Ninja philosophy.", videoCount: 9, icon: "Search", gradient: "from-red-500 to-rose-600", featuredVideos: [{ id: "0yQI3bcSrBo", title: "The best lead generation activity ever!" }, { id: "cYEukn_34Uw", title: "Building a Tribe: Lessons in Community and Success" }, { id: "WAUbcNRqo5k", title: "Dunbar's Number and Building Your Tribe" }, { id: "_9s1laeiYGo", title: "Best Lead Generation Activity" }, { id: "GLmCFotxmEY", title: "Getting to Know Your Vendors" }] },
  { id: "real-estate-reviews-and-presentations", name: "Real Estate Reviews & Market Presentations", description: "Creating and hosting real estate review events and market update presentations to position yourself as the trusted advisor in your market.", videoCount: 8, icon: "BarChart3", gradient: "from-teal-500 to-emerald-600", featuredVideos: [{ id: "FTwYZnYdBXY", title: "Harnessing the Power of Data and Real Estate Reviews" }, { id: "zvXLZyR2nD4", title: "Turning Real Estate Reviews into Transactions" }, { id: "FGlj1Okm6Gk", title: "Perfecting Real Estate Reviews for Today's Marketplace" }, { id: "NkAFeWfAq5E", title: "Announcing the Monthly Ninja Sales Meeting" }, { id: "ge6ZluujyzI", title: "The steps in MLS to prepare a RER" }] },
  { id: "value-service-and-client-experience", name: "Value, Service & Client Experience", description: "Delivering exceptional value, creating memorable client experiences, fabled service, and going above and beyond to make clients feel genuinely cared for.", videoCount: 7, icon: "Star", gradient: "from-amber-500 to-yellow-600", featuredVideos: [{ id: "oVLNmVuyVtU", title: "Creating a Positively Unique Experience for Your Clients" }, { id: "gcR4KkChDlU", title: "For Ninjas creating Fabled Service is everything" }, { id: "p15YL4syGZI", title: "Be the source of information" }, { id: "q2mIWrCDK2E", title: "Setting Yourself Apart from the 'Order Takers'" }, { id: "TW4fLeFqS4M", title: "What Exactly Does My Client Want?" }] },
  { id: "branding-marketing-and-technology", name: "Branding, Marketing & Technology", description: "Building your personal brand, video marketing, leveraging technology, digital presence, and using tools to enhance (not replace) your relationship-based business.", videoCount: 6, icon: "Megaphone", gradient: "from-blue-500 to-cyan-600", featuredVideos: [{ id: "ayVN-nf5D2I", title: "Delivering Peace of Mind with Step-by-Step Tech" }, { id: "YiPqjNy6ao8", title: "Showcasing Your Value in the Digital Age" }, { id: "ZMwUiUZtFVI", title: "Postcards: Doing Them the Right Way" }, { id: "Y4VeVAy4uOM", title: "Video Makes the Real Estate Star" }, { id: "VKJd7NCwWts", title: "A Couple Amazing QR Code Tools" }] },
  { id: "negotiation-and-transaction-management", name: "Negotiation & Transaction Management", description: "Negotiation techniques, managing complex transactions, handling the NAR settlement, and guiding clients smoothly from contract to close.", videoCount: 5, icon: "Scale", gradient: "from-gray-500 to-slate-600", featuredVideos: [{ id: "GSzVzqoGREA", title: "Mastering the Art of Negotiation" }, { id: "zctlvR61c3w", title: "Navigating the NAR Settlement like a Ninja" }, { id: "sJPBmkyqHZk", title: "Piecing Together the Transaction Puzzle" }, { id: "Np43CvzpxyI", title: "Negotiate Home Plate" }, { id: "qLbAcnTrxEA", title: "Acceptance Stage Management" }] },
  { id: "covid-19-and-crisis-response", name: "COVID-19 & Crisis Response", description: "Content addressing the COVID-19 pandemic and how real estate agents can adapt their Ninja practices during times of crisis and uncertainty.", videoCount: 4, icon: "ShieldAlert", gradient: "from-red-500 to-orange-600", featuredVideos: [{ id: "eyt9klIATyM", title: "Larry Kendall's COVID-19 Response" }, { id: "zr2wR0vWxNA", title: "Ninjas and COVID-19" }, { id: "GjxTaOTgbVw", title: "More Ninja Ideas around COVID-19" }, { id: "QoxskHww5kE", title: "Physical distancing not social" }] },
  { id: "open-houses", name: "Open Houses", description: "Strategies and best practices for conducting successful open houses as a lead generation and relationship-building opportunity.", videoCount: 2, icon: "DoorOpen", gradient: "from-green-500 to-emerald-600", featuredVideos: [{ id: "PmkSXY3o6L8", title: "Strategy Session to Upgrade Your Open Houses" }, { id: "PprswnVmwqk", title: "Reaping the Rewards of Open Houses" }] },
]

export const allVideos: Video[] = [
  { id: "4qMoGTx4b0Y", title: "Action Tip #579: Handle hard better with the right team!" },
  { id: "O-FuU1mRUbc", title: "How to Build a Team That Actually Works" },
  { id: "Jd3U-Lcs4b8", title: "Action Tip #578: Done is Better Than Perfect" },
  { id: "NYIhCLe-ZFo", title: "Why 'Flow Fixes Everything' in Real Estate" },
  { id: "r1QbMt3Xjto", title: "Auto-Flow 101: Why Flow Fixes Everything" },
  { id: "YXjDBlk1mVc", title: "Action Tip #577: Dream It. Plan It. Do It. Celebrate It." },
  { id: "T4Gh5UuotBc", title: "Don't Forget to Have Fun" },
  { id: "TRHFbYodxvA", title: "The Pivot from Buying Leads to Building Relationships" },
  { id: "fTZmX-Cgw9U", title: "Bonus Episode: The Gold is in the Ghosts Sales Meeting" },
  { id: "LCel0MB8Bw0", title: "Stop Selling. Start Solving. The Second Cornerstone of Ninja Selling" },
  { id: "ybOd55CEfLw", title: "Action Tip #575: Why You're Hesitating to Reach Out" },
  { id: "n-_1Xu5ZUpY", title: "Rebuilding on Purpose Through Flow" },
  { id: "JAgIsaRpZ5c", title: "The Ninja Scorecard - Your Plan for Consistency" },
  { id: "bWObJe8cwbc", title: "Action Tip #574: Detach from the Outcome" },
  { id: "eE1qHKc-B6o", title: "From the Hamster Wheel to Deep Connections" },
  { id: "VekdkcTX5uE", title: "Best Year Yet in Brooklyn" },
  { id: "nTnsOdVZmao", title: "Action Tip #572: Did You Make a Reservation" },
  { id: "MJfKBiQJZpk", title: "This is Happening For Me, Not To Me" },
  { id: "WC_nezGrWJ4", title: "Live From The Ninja Installation: Trust the Process, Then Watch the Results" },
  { id: "IS1470U8xiM", title: "What is Personal Mastery in Ninja Selling?" },
  { id: "4lwMtg1zP18", title: "Personal Mastery: The First Cornerstone of Ninja" },
  { id: "ElBtOoFanoE", title: "Action Tip #570: Flip the Switch" },
  { id: "ropiLhLsfk0", title: "If You Could Wave Your Magic Wand" },
  { id: "49PhQ8nwzjM", title: "Action Tip #568: This Simple Action Creates Referrals (and it’s Not Selling)" },
  { id: "Bvqzlo3M4CU", title: "Action Tip #567: Your 2026 Word of the Year" },
  { id: "2WKDpsTEOTY", title: "Ninja In A Nutshell - An Overview of the Ninja Selling System" },
  { id: "tgFqhzIMZTU", title: "Action Tip #566: Holiday Conversations That Actually Matter" },
  { id: "9OR8ztxjifs", title: "Momentum Isn't Loud - It's Consistent" },
  { id: "qzT4SZFcv_k", title: "Action Tip #565: Create Your Holiday 8×8" },
  { id: "0NX-NQDh3Ng", title: "20 Hours. 100 People. Zero Burnout." },
  { id: "euuyZhIeP2M", title: "Action Tip #563: A Thanksgiving Action Tip That Could Make Someone’s Week" },
  { id: "yu_7yzbLHfU", title: "How To Be Consistently Magnetic Even When Life Throws You A Curve Ball" },
  { id: "LZ0Bq043RRs", title: "Action Tip #562: While Others Coast, Ninjas Double Down" },
  { id: "9JWJz5pf0Rk", title: "The Ninja Couple: From Military Precision to Real Estate Success" },
  { id: "APK1mycdSM0", title: "Action Tip #561: This Economic Indicator Could Be Your Next Opportunity" },
  { id: "Bt0I1piZ71I", title: "\"Do I Pursue a Solo Career Or Do I Form a Team?\"" },
  { id: "Rk_yvHdW0ys", title: "How to Intentionally Create Change" },
  { id: "vEooMYXxK3Y", title: "Action Tip #559: Don't Miss the Assembly" },
  { id: "N4EbHY3j-KM", title: "80 Years Worth of Stellar Advice for Today's Agent" },
  { id: "tp3-f7IfZNI", title: "Action Tip #558: Finish Strong by Reviewing What Worked (and What Didn’t)" },
  { id: "MO_CPEilpfw", title: "How to Have Consistent Volume in an Inconsistent Market Using Consistent Routines" },
  { id: "5PjAt7AESSA", title: "Action Tip #557: Guide With Clarity...Not Fear" },
  { id: "Y8Vss_uaNl8", title: "How to Turn a Dream into a Reality" },
  { id: "1lxD6ibUcG0", title: "Mastering the Ninja Planner with Creator Eric Hardy" },
  { id: "7K8UEtNcqHs", title: "From Burnout to Breakthrough: Lonney Gordon's Journey to Authentic Flow" },
  { id: "K08vG_LKc9o", title: "Action Tip #555: Now is the time." },
  { id: "epKxHFOiELA", title: "Throw Out the Rulebook: Opportunity Inside the Compass x Anywhere Real Estate Merger" },
  { id: "D5A55uPxzTY", title: "The Opportunities in Change - Larry Kendall, Jack Miller, Mike Staver" },
  { id: "5rzPb10nqKo", title: "Action Tip #554: Farmers don’t just plant… they prepare" },
  { id: "Yui0U6Un3l0", title: "From Travel Crisis to Real Estate Fortune" },
  { id: "k1n86XHg3Pk", title: "Action Tip #553: People Hire How They Feel Around You" },
  { id: "lvFwUzy81Lc", title: "Ninja Hacks for Exponential Growth with Martin Gallant" },
  { id: "hq94Ishz1A8", title: "Sell Your Stalled Listing with a Seller's Offer" },
  { id: "szgSkjzwKSg", title: "Action Tip #551: Double Down on Gratitude" },
  { id: "lQV3q7XJ7_0", title: "Simple Shifts for a More Profitable Business" },
  { id: "qv9Rt4-LWE4", title: "Action Tip #550: 30 Minute Morning Reset" },
  { id: "VFJZeD6iWU8", title: "Building Unshakable Confidence for Real Estate Agents" },
  { id: "bWNfhLrXpgs", title: "Action Tip #549: Make the Shift from “A Realtor” to “My Realtor”" },
  { id: "3iLTcuHEQ-Y", title: "From Classroom to Closing: How a College Course Launched a Ninja Career" },
  { id: "iW01Yxeptaw", title: "Action Tip #548: Tune in to Opportunity" },
  { id: "MBRDeWUphrc", title: "Are You Creating Buyers?" },
  { id: "5DmxfgQVyko", title: "Matthew Gardner's Housing Market Talking Points" },
  { id: "LoRzDXnzgDI", title: "How a Rookie Did $28M in His First Year: Koby Bishop's Blueprint for Success" },
  { id: "v7ZiyYl70YA", title: "Action Tip #546: Neighbor Notes for Your Buyers" },
  { id: "_4yJOO4iWxQ", title: "Your Mid-Year Halftime Huddle" },
  { id: "2uwdfYghEcU", title: "Action Tip #545: Start Your Stop Doing List" },
  { id: "hxf_xfuVBkM", title: "Mastery of Yourself" },
  { id: "NyGbnpFRy24", title: "The Art of the Question: Next-Level Conversations with Erik Zimmerman" },
  { id: "Vyq2tnJynyQ", title: "Action Tip #544: Use Ninja on Your Most Important Client" },
  { id: "azOsX53XCSU", title: "Ninja Selling Guide Camp" },
  { id: "5LcsTudzveU", title: "The Reverse Offer" },
  { id: "9TrLAqEFUbw", title: "Action Tip #543: The Reverse Offer (aka Offer to Sell)" },
  { id: "AGpbzfWbJFo", title: "Larry Kendall's Summer Plans" },
  { id: "T1uRJ0n26CM", title: "Action Tip #542: Build Your \"Notes On The Go\" Kit" },
  { id: "GVD4Kr0x3j4", title: "How to Build a Ninja Company: A Blueprint from Jenny Usaj" },
  { id: "fge6q4Qbgj8", title: "Frictionless Referrals: Introducing Referral Flow and the New Find a Ninja" },
  { id: "HhkVvydPVDw", title: "Action Tip #541: On a Scale Of 1-10" },
  { id: "LpuIOdDIxWU", title: "How To Be a Resort Market Ninja" },
  { id: "0bFRFS8cIlU", title: "Action Tip #540: Know the Best Deal in Your Market" },
  { id: "26fFCYtAu9s", title: "The Team Leader Blueprint - by Ninja Coaching" },
  { id: "NkAFeWfAq5E", title: "The Return of the Sales Meeting: Announcing the Monthly Ninja Sales Meeting with Larry Kendall" },
  { id: "IptK2wttAR0", title: "Action Tip #539: Power Your Summer Flow" },
  { id: "-1tQZNgfYS0", title: "June Live Action Tip: How’s the market?" },
  { id: "Qme0HO1Q5G0", title: "Create More, Work Less" },
  { id: "8KlbnMzRmRQ", title: "Navigating Seller Risk: A Modern Approach to Pricing Conversations" },
  { id: "kTDF9KQJjKw", title: "The Heart of a Ninja: Building a Thriving Team and Business with John Newman" },
  { id: "61Tp0OD0B8s", title: "Action Tip #538: Pricing Right" },
  { id: "Vr0tsN3zPPs", title: "Action Tip #537: Referral Flow" },
  { id: "enPY66udOro", title: "How to Go From Earning $8,000 a Year to $308,000 a Year in Five Years" },
  { id: "PmkSXY3o6L8", title: "May Ninja Kickoff: 20-Minute Strategy Session to Upgrade Your Open Houses" },
  { id: "tRFe9Z1vKC8", title: "Your Ninja Nine Challenge with Julianne Rawlins" },
  { id: "eohkaXms_H4", title: "Action Tip #536: Know Your Numbers" },
  { id: "ihzeS_VUaQ0", title: "A Community of Raving Fans" },
  { id: "LtF7nlt2lYk", title: "The Level Up Moment: Leading with Mindset, Skillset, and Action featuring Jennifer Lind" },
  { id: "9ltHuRBZXqE", title: "Shift Your Mindset with One Sheet of Paper" },
  { id: "FZ-VDXl7X0s", title: "Action Tip #535: Deepen Any Relationship" },
  { id: "vkJb4QQyOXM", title: "Live Action Tip Webinar: Clarity is Power" },
  { id: "cYEukn_34Uw", title: "Building a Tribe: Lessons in Community and Success from a 50-Year Rock Band" },
  { id: "L1wX3OrOjsY", title: "Action Tip #534: Unlocking Homeownership: It's Not Just About Income." },
  { id: "o00RZgceB2s", title: "Tripling Your Business: Jim Knight on Mindset, Skillset, and Action" },
  { id: "vAM7IZDYTUc", title: "Action Tip #533: The One-Two Punch To Transform Your Flow" },
  { id: "6V0uatxS_XM", title: "Springtime Mojo" },
  { id: "OEzhhzJL2CU", title: "Action Tip #532: Electronic Notes" },
  { id: "kF7uqtedbG0", title: "Find Your Pickleball" },
  { id: "Np43CvzpxyI", title: "Action Tip 531: Negotiate Home Plate" },
  { id: "qKRDyrp5aoc", title: "Tales from the Road: Insights and Opportunities in Today's Real Estate Market" },
  { id: "BI0wFgSwxZA", title: "Action Tip #531: Pre-Listing Packets ( March Kickoff)" },
  { id: "K3rF7rrs0rg", title: "From Snowboarder to Ninja: First Impressions from the Ninja Installation" },
  { id: "v54aGsu26Xs", title: "Action Tip #530 Deliver Confidence And Clarity" },
  { id: "tUYd92RyZ_E", title: "The $1 Million Secret with Amy Balewicz" },
  { id: "NWkrSvWHoJ8", title: "Action Tip #529: The Gap And The Gain" },
  { id: "9IrI5eCIGNg", title: "The Secret to Guilt-Free Client Follow Up" },
  { id: "MrrcmrIzmKg", title: "Action Tip #528: Be Referable" },
  { id: "JD17rt5YqfE", title: "Unlocking the Power of Your Hot and Warm List: Strategies from Joe Robert and Mark Johnson" },
  { id: "INs9lxeeLrg", title: "February 2025 Kickoff Webinar: Building Your Warm List" },
  { id: "zvXLZyR2nD4", title: "Turning Real Estate Reviews and Events into Transactions with Lori Chamberlain and Lisa Connors" },
  { id: "kE_KsbmJBng", title: "Become the CEO of Your Relationships with Meaghan Austin" },
  { id: "guptRmiGo0I", title: "How to Effectively Hand Off Your Real Estate Business" },
  { id: "kLf6JsfYWKM", title: "Bounce Back" },
  { id: "Nw0jmMDwjoA", title: "What's Your 2025 Word of the Year?" },
  { id: "95-QBhCjZwo", title: "Make 2025 Your Best Year Ever in Real Estate" },
  { id: "v9qteF2VDx8", title: "Holiday Flow Ideas" },
  { id: "UedLGJTp9KU", title: "Want More Closings? Master Your PIE Time" },
  { id: "7e1YLIXy0Vs", title: "Ninja Selling November 2024 Kickoff Call" },
  { id: "6TyrS31knKs", title: "Business Planning" },
  { id: "sp2ZOTql8lM", title: "The Secret To Effortless Real Estate Referrals" },
  { id: "zmXDMX3y84A", title: "A Servant's Heart" },
  { id: "k5IydNtQNxU", title: "The Winter Soldier" },
  { id: "j3leXdBn0BY", title: "Trying Something New" },
  { id: "0L1zmWMwvaE", title: "Ninja Installation Takeaways You Need To Know" },
  { id: "n9ne29mfYyw", title: "Become a Top Producer With THIS Mindset" },
  { id: "wYvdilqyLWY", title: "Larry Kendall Answers Your Questions" },
  { id: "-QLdV8uPtZE", title: "How to Finish 2024 Strong and Set Up for 2025 Success" },
  { id: "Zp3tEpdV6C0", title: "NOLA Property Guys Explain the Real Estate Vibe Check" },
  { id: "c7Z6owTLHgc", title: "Why This Realtor Doesn't Fear Market Shifts" },
  { id: "tJYZAah4q_M", title: "How Jonathan Spears Built A $500M Team" },
  { id: "qrYXzXjavVw", title: "He Wrote The Book On A Drama Free Life" },
  { id: "WxPQzM6iqTU", title: "Video Version - How To Generate Referrals Without Asking with Larry Kendall and Stacey Brown Randall" },
  { id: "NxnbMw5jymE", title: "How To Generate Referrals Without Asking" },
  { id: "AoJim8CbTzg", title: "5 Questions That Turn Conversations Into Clients" },
  { id: "xCMEE8zORRk", title: "Action Tip #505: What is the best CRM?" },
  { id: "TVSjxqel9Ns", title: "Why Bother Asking? (You Should!)" },
  { id: "TUSgP6pL-Ho", title: "The Ninja Selling Podcast Episode 586 / Ninja Coaches: Why Agents Use Them To Win" },
  { id: "dRXTDAfGp70", title: "Ninja Coaches: Why Agents Use Them To Win" },
  { id: "YViDcHmX2-0", title: "Action Tip #503: Revisit the Tools You Already Have" },
  { id: "ar5xPA6PlKg", title: "Action Tip #502: Track Your Ninja Nine" },
  { id: "bRbIAV1e_C8", title: "The Future Of Ninja Selling Revealed" },
  { id: "EX_26NqI8oU", title: "Ninja Action Tip #499: The Problem is the Solution" },
  { id: "EwAqaEdg3eE", title: "The Opportunity Ahead with Garrett, Matt, & Larry" },
  { id: "FsYR0TRBa5Q", title: "Weekly Action Tip #498: If They Say It - They Own It" },
  { id: "maMPuSTFUVQ", title: "Over 3.5 Million Downloads Later: What We've Learned" },
  { id: "JUm8tBd6gLg", title: "Seeing the Change on the 15th Day" },
  { id: "g1DjyqhZz4g", title: "Building Your Dreamer Teams" },
  { id: "890H9U9E-SA", title: "\"Your Opportunity in Your Hands Right Now!\"" },
  { id: "qGhHgySUNV4", title: "Maintaining \"I\" Contact" },
  { id: "84aIEIGr5Z4", title: "Be the Brand" },
  { id: "dFN_kwG_mAM", title: "Local Area Networking" },
  { id: "wIWIPzUTMyU", title: "Your Ideal Customer" },
  { id: "mZAWJLUCUkc", title: "Put Your Feet Down" },
  { id: "gyTv6IyLlFY", title: "Why Haven't I Been Doing This the Entire Time?" },
  { id: "1C5CW_jxx7c", title: "Communication Elevation" },
  { id: "h0dDjyF32Eg", title: "Recognizing Opportunity's Knock" },
  { id: "MzNpTmo6Lf4", title: "Keeping Time on Your Side" },
  { id: "5bQJqtRTxtE", title: "Taking the Lead" },
  { id: "XK9zerTF4-Y", title: "Thawing Out the Information Overload Freeze" },
  { id: "RxENbmZtSeU", title: "Learning That It's Awkward Until It's Not" },
  { id: "ftqxEQvV0M0", title: "Ninja Coaching Spotlight with Christine Moore and Tracy Peterson-Nienaber" },
  { id: "7U0_aVWhjTk", title: "Knowing When to Raise the Bar" },
  { id: "IC3rQM9LbCU", title: "Growing with the Flow" },
  { id: "Pwgg1WvhiBI", title: "One For the History Books" },
  { id: "r7HkJjS27T0", title: "Maintaining the Personal Touch in a Digital Age" },
  { id: "2scB4wEORNs", title: "\"Please Stop Predicting the Future\"" },
  { id: "zctlvR61c3w", title: "Navigating the National Association of REALTORS® Settlement like a Ninja" },
  { id: "eiDjJkgyJfU", title: "\"Houston, We Have an Opportunity\"" },
  { id: "gOb5KWsM9Vg", title: "Riding The Routine Road to Success" },
  { id: "dPj3i1HSGKU", title: "Energy Management for Client Engagement" },
  { id: "BKgsYbjJmU4", title: "Free Time vs. Fun Time" },
  { id: "-GvT0jBhB8c", title: "Ninja Coaching Spotlight with Patty Schmitz-Thursam and Natalie Davis" },
  { id: "zA_fJFIhUec", title: "\"Whenever You Win, People Will Immediately Assume…\"" },
  { id: "mADUAeTtgAU", title: "\"This Is Why Ninja Was Built\"" },
  { id: "-AETTR50jfg", title: "Playing The Long Game" },
  { id: "UKHSxpDnKHg", title: "It's Not Just About Numbers" },
  { id: "u_BjOm8VI04", title: "Ninja Coaching Spotlight with Travis Beers and Jon Hill" },
  { id: "k4sTso2LEBM", title: "Unearthing the Beet and Potatoes of Successful Phone Calls" },
  { id: "3CgVWorsQ38", title: "Ninja Action Tip #486: Schedule a Meeting with Yourself" },
  { id: "tvAgwEuT1oA", title: "Trust Never Sleeps" },
  { id: "2GWGk4kgKac", title: "Consistency, Commitment, and Success by the Numbers" },
  { id: "FgXHdIZC6KE", title: "Ninja Action Tip #485: You are the Quarterback" },
  { id: "eK3DBHn3GiI", title: "Achieving Balance in a 24/7 Industry" },
  { id: "PevRygUYj-I", title: "Ninja Coaching Spotlight with Joan Goode and Jen Gamez" },
  { id: "66GiOZ9elH0", title: "Critical Calendar Control" },
  { id: "VKJd7NCwWts", title: "A Couple Amazing QR Code Tuells" },
  { id: "VpEyXIfUOqY", title: "Managing the Busy in Your Business" },
  { id: "xgIUPX5Cee8", title: "Fulfilling the New Year's Promise" },
  { id: "xXePRJRourQ", title: "Ninja Coaching Spotlight with Lonney Gordon and Jen Fidler" },
  { id: "RZuRm_wcchs", title: "Taking Care of the Upstream" },
  { id: "GLmCFotxmEY", title: "Getting to Know Your Vendors" },
  { id: "ik7m9TWp5Kk", title: "Leaning into Lifelong Learning" },
  { id: "pSttNDhWSxU", title: "It's Stop Blocking and Start Depositing Time" },
  { id: "NTsUTd6p0Ok", title: "Ninja Coaching Spotlight with Christina O'Neal and Mark Johnson" },
  { id: "wXxKGuVdakY", title: "Fostering Growth by Embracing Change" },
  { id: "b5FL-jLqMcs", title: "Managing Interest Rate Perceptions" },
  { id: "kUlREjzMBf4", title: "Close Encounters of the Most Memorable Kind" },
  { id: "A2HS-XC2lHs", title: "Kicking Off 2024 with the \"Digital Commute\"" },
  { id: "wTnD6ZFT0-4", title: "Ninja Coaching Spotlight with Alice Toy and Jen Gamez" },
  { id: "T578Wr8oYo4", title: "Little Improvements That Generate Big Success" },
  { id: "Q9Zyi6GhFgw", title: "Celebrating Every Day" },
  { id: "dxY5eN8tqJg", title: "Get the Skills Group Scoop" },
  { id: "_es7afdNUT4", title: "Becoming the Market Expert" },
  { id: "5ZJw0tgXyb8", title: "Ninja Coaching Spotlight with Abby Baker and Heather Matz" },
  { id: "AZ2IUWj9Zt8", title: "Embracing an Attitude of Gratitude with Mr. Thank You" },
  { id: "DcqndNk7xSI", title: "Taking Zero Off the Table" },
  { id: "Y7Tr6O0W4Zs", title: "What's Your Money Up To?" },
  { id: "WyGAcuzg-cw", title: "\"One of Three Things\" with Larry Kendall" },
  { id: "RQuYhWYphHk", title: "Ninja Coaching Spotlight with Susan Saving" },
  { id: "WNHWvneMbjY", title: "Ninja Installation Q&A with Dennis Giannetti" },
  { id: "GeXsrTdDJXY", title: "Wisdom, Guidance, and Reassurance from Larry Kendall" },
  { id: "taBkLlwdCn8", title: "Happy Thanksgiving from Ninja Selling!" },
  { id: "M8tvXIRwOnk", title: "Navigating Life's Curveballs" },
  { id: "Mdn11Bsk1IM", title: "Ninja Coaching Spotlight with Melissa Herdman" },
  { id: "padu2VJmRYw", title: "Defining Your Own Success" },
  { id: "LQsmLafvj5s", title: "Keep the Selling Homes Fire Burning" },
  { id: "sEwSnIBmt3w", title: "\"To Thine Own Self Be True\"" },
  { id: "hMqiTvVwZik", title: "The Power of Presence in Your Clients' Worlds" },
  { id: "yo9UZwm61AQ", title: "Ninja Coaching Spotlight with Michael Doyle" },
  { id: "iRBxDL_r10s", title: "Understanding and Outperforming the Market" },
  { id: "WZfToQUja7Y", title: "Planning for Even Greater Success in 2024" },
  { id: "TwnUSZBQieY", title: "Making Positive Waves with the Law of Precession" },
  { id: "MmJYhYTLIWo", title: "Whose Goal Are You Chasing?" },
  { id: "09Qjx1kgIbw", title: "Ninja Coaching Spotlight on Allie Hatley and Lisa Connors" },
  { id: "p5rxnJ0lYSg", title: "Feasting on Balance and Sustainability" },
  { id: "_D4z-OOqrPA", title: "Baking Success into Your Business Cake" },
  { id: "ANUWqpbSDq4", title: "Gifting Yourself Presence" },
  { id: "GSzVzqoGREA", title: "Mastering the Art of Negotiation" },
  { id: "1SRiwYN1114", title: "Ninja Coaching Spotlight on Renee Bert and Mary-Clare Hill" },
  { id: "t1NgbYAkIVo", title: "Expectations, Communication, and Reputations" },
  { id: "xBb-y1zRHsM", title: "The Big 5-0-0!" },
  { id: "TC6Ta7BsUzI", title: "Balancing Passions and Obligations" },
  { id: "gVF4tckHw5I", title: "Waking Up to Success" },
  { id: "8-B8RO455ME", title: "Ninja Coaching Spotlight on Peggy Shanklin and Shelly Culbertson" },
  { id: "4TBBZBzr2rA", title: "Opening Up Inventory and Opportunity with Contingent Offers" },
  { id: "px3xQjl_oJA", title: "Celebrating Realtor Safety Month with Natalie Davis" },
  { id: "S2_v8-wrAo0", title: "Speaking of Dreams" },
  { id: "ZMwMzNic2oM", title: "Dream a Little Dream" },
  { id: "hLAFZMMcaHA", title: "Introducing The Ninja Coaching Spotlight" },
  { id: "wBIRkcmEwxo", title: "When You Want It More Than the Client Does" },
  { id: "GaBzpaS3_Ts", title: "Accelerating Your Business Machine on the Straightaways" },
  { id: "JyBZsfA1VCg", title: "What Are the Pros and Cons of the 30 Year Mortgage?" },
  { id: "gqmT49Mz5yE", title: "The Confusion Solution" },
  { id: "jjy2-zZq4VU", title: "Choosing Sustainable Success Over Quick Fixes" },
  { id: "Y9_wEmE_SPQ", title: "Been There, Done That" },
  { id: "Qeb0N_idgaM", title: "Firing Up the 'Long-Term Machine'" },
  { id: "zpfJpZEzLMM", title: "The Ripple Effect of Effortless Information Access" },
  { id: "BGE04tKHcww", title: "\"Let's Make It Really Simple\"" },
  { id: "4OsMj06CZ0Y", title: "Going that Extra Mile on the Road to Success" },
  { id: "0PJvFD2FVtQ", title: "Taking this Time to Sharpen Your Skills" },
  { id: "awpCk4zyd3g", title: "The Power of Strategic Pricing" },
  { id: "q2mIWrCDK2E", title: "Setting Yourself Apart from the 'Order Takers'" },
  { id: "tV3mHE4MUKA", title: "Grow with the Flow" },
  { id: "-OQtRCUxVmc", title: "Tapping into Collective Wisdom" },
  { id: "sJPBmkyqHZk", title: "Piecing Together the Transaction Puzzle" },
  { id: "29QV5yG5hXE", title: "Goal Pacing Your Way to a Successful Year" },
  { id: "Gil3ipcxC6o", title: "The Uplevel is in the Details" },
  { id: "3Ab9ziXAWH8", title: "Keep Your Engine Tuned" },
  { id: "GP65V2uhckk", title: "Moving Clients Off the Fence and Into a House" },
  { id: "6dAKOAO3yKs", title: "Giving Your Family the Credit They Deserve" },
  { id: "1tZ-oHhh-rw", title: "Welcome to the Redundancy Department of Redundancy" },
  { id: "AW-8Hk9KyqM", title: "Everyone Has to Pee" },
  { id: "3nwp3YhKsOk", title: "\"What's Going on in the Market?\"" },
  { id: "cA79L9ActJM", title: "The Power of Handwritten Notes in a Digital World" },
  { id: "QXg3CIRdgeA", title: "Maintaining Authenticity in an AI World" },
  { id: "O8ukIUoinhw", title: "Choosing the Right Vehicle on the Road to Life-Work Harmony" },
  { id: "cTcyAKSwHOI", title: "To Scale or Not to Scale" },
  { id: "ly9r2hU_iy0", title: "Negotiating Sellers' Specific Financial Expectations" },
  { id: "Bvy8Jr6fCzI", title: "When Good Properties Just Won't Sell" },
  { id: "5iBckOvnw38", title: "Increasing Your Return on Time" },
  { id: "D5PM7ePMvhc", title: "Pitching Coaches" },
  { id: "necbcQ7lLqs", title: "Finding Success in Flow Motion" },
  { id: "LGc_DR8ZVxI", title: "Debunking the Low Interest Rate Myth" },
  { id: "ayVN-nf5D2I", title: "Delivering Peace of Mind with Step-by-Step Tech" },
  { id: "Y4VeVAy4uOM", title: "Video Makes the Real Estate Star" },
  { id: "hMtYU96VORc", title: "Developing Dynamic Databases" },
  { id: "8LyxNuLuCXA", title: "Revving Up Your Systems" },
  { id: "MtjcfMhP4mQ", title: "Phone Calls, Texts, and Effective Communication" },
  { id: "VnZ6u1nWdb4", title: "Wake-Up Money with Larry Kendall" },
  { id: "aBaWQvQ6U1g", title: "Integrating Ninja into Your Existing System" },
  { id: "TW4fLeFqS4M", title: "What Exactly Does My Client Want?" },
  { id: "-XlMibSeayI", title: "Assistants Assistance with Shelley Culbertson" },
  { id: "TR27GMGffdI", title: "Using Fear of Judgment to Your Advantage" },
  { id: "oVLNmVuyVtU", title: "Creating a Positively Unique Experience for Your Clients" },
  { id: "wWXuHsHGDZ8", title: "Reigniting Your Passion" },
  { id: "owLVBw8cxS0", title: "Quality vs. Quantity" },
  { id: "Ssgc1LZQ-V4", title: "Value, Relationships, and Referrals" },
  { id: "6bO9frs44A8", title: "When Agents Sell Their Own Homes - The Bonelli Files" },
  { id: "OWLR9yHxuVA", title: "Balancing Emotional Attachment and Detachment" },
  { id: "X2PP_GJ_a5M", title: "When Your Client Is Both a Buyer and a Seller" },
  { id: "FAYy_dNvmoE", title: "Partnering for Success in Any Market: A Client's Perspective" },
  { id: "VdnEsx0U13s", title: "Achieving Sustainable Success" },
  { id: "-mLSYbZRTrs", title: "Getting the Gang Back Together Again" },
  { id: "2l_uJ-55POw", title: "Charging Up Your Hour of Power" },
  { id: "VrLqD8shRZ8", title: "Maintaining Your Balance when 'Drinking from a Fire Hose'" },
  { id: "bYnWVpkeZHs", title: "The Keys to Successful Listing Consultations" },
  { id: "dTw8orpkvzo", title: "Loved the Installation! Now What?" },
  { id: "WRL3etfFh1A", title: "The Ninja Perspective on Pop-Bys" },
  { id: "qLbAcnTrxEA", title: "Acceptance Stage Management" },
  { id: "YiPqjNy6ao8", title: "Showcasing Your Value in the Digital Age" },
  { id: "aAbcpV-V1C4", title: "Deciding to be Disciplined" },
  { id: "PrJQXXqm2lg", title: "The Secret to Success in Any Market" },
  { id: "CO1Fr19kH9s", title: "Reviewing Real Estate Reviews" },
  { id: "dgsy9cWNRMg", title: "Keeping Your Word" },
  { id: "nYXnTmvmG7w", title: "Fishing in Your Database" },
  { id: "o2qK4G4YthQ", title: "Minding Your Own Business" },
  { id: "Q5nHAivP0Us", title: "Flicking the Switch" },
  { id: "Jog4Seaftc0", title: "Step Into The Process" },
  { id: "WAUbcNRqo5k", title: "Dunbar's Number and Building Your Tribe" },
  { id: "IoR_F4tY_e4", title: "Channeling the Power of Self-Salesmanship" },
  { id: "wCQ1JAyv-oE", title: "Is Money Walking?" },
  { id: "RIdDMFSCZk8", title: "Personal Connection and World Perception" },
  { id: "msJDr0N7Pq8", title: "Self-Care: The Holiday Edition" },
  { id: "ZdDXXRleW58", title: "Customer Relationship Management Systems" },
  { id: "H3FIY9EFIB0", title: "Moving Goals from Realistic to Incredible" },
  { id: "BnGc8ZX3kKk", title: "Always Being There for Your Clients" },
  { id: "14o3seZuI4U", title: "Are You Fishing in the Right Pond?" },
  { id: "qrM1kIQ9KMw", title: "Choosing Inspiration Over Comparison" },
  { id: "6QR1GHa8nOk", title: "Referrals, Relationships, and Rocking the Ninja Nine" },
  { id: "NlHqXQjgXfM", title: "Going Through Five Stages of Change" },
  { id: "55L-7KiSGvA", title: "Matt and Garrett Host the Princeton Mortgage Panel" },
  { id: "q62YFad0nec", title: "Making Everyday Thanksgiving Day" },
  { id: "3W_QeKRoi8w", title: "Understanding Your Business Model to Determine Next Steps" },
  { id: "Klv6V5xAm58", title: "Getting Un-Stuck" },
  { id: "vMer6syr9YM", title: "Weekly Action Tip #216: Positive Emotional Energy" },
  { id: "MHIRCf5G1Xo", title: "Consistently Showing Up to Practice with Ninja Systems" },
  { id: "_zlOkMd-GFo", title: "Feedback or a Rating?" },
  { id: "Pb3Lkbb7GuA", title: "Tune Yourself for Optimal Performance this Holiday Season" },
  { id: "zLanQ-f9A5E", title: "Know Your Market Well" },
  { id: "lkuDSKYKz3I", title: "It's That Time of Year Again!" },
  { id: "lx-SJrJxeSM", title: "Letting Go of the False Narrative of Yesterday" },
  { id: "PlsneO8wNcg", title: "It's Episode 400 and We're Talking Parades!" },
  { id: "S-Ai8ptxhRA", title: "Show Up! Dress Up?" },
  { id: "PprswnVmwqk", title: "Reaping the Rewards of Open Houses" },
  { id: "lpQYTbv42kY", title: "The Deciding Factor for Success" },
  { id: "5Pi1-Ke9ymQ", title: "Ninja Weekly Action Tip #211: Plan Before There is Demand" },
  { id: "FY-b6uEiCxA", title: "The Benefits of Leading a Ninja Life with Rob Henderson" },
  { id: "xOOJlRJkpQM", title: "The Legend of the 'Normal Market'" },
  { id: "vWmF50xuRz8", title: "Ninja Weekly Action Tip #210: Know Your Market" },
  { id: "zvMPMNVLjUk", title: "Is the Sky Really Falling?" },
  { id: "EmuCqfEdeBE", title: "Data: Why it Matters" },
  { id: "pwNR7vwwM7E", title: "Failure to Launch" },
  { id: "QKAX8sNdmHw", title: "Pay Yourself First" },
  { id: "dh93dTKHFAc", title: "Weekly Action Tip #207: Habits 6, 7 and 8" },
  { id: "6RAMss_AGbo", title: "The Law of Precession" },
  { id: "OF11O2ILTbY", title: "Level Up with Custom Flow" },
  { id: "bCh7rJC6ug4", title: "Weekly Action Tip #206: Accept results and improve" },
  { id: "I1vl8n_I9Wk", title: "The Game Is Rigged in Your Favor" },
  { id: "wr5uWE2Gzqg", title: "Calming the Storm of Changing Inventory Levels" },
  { id: "Z2LOQWayRmc", title: "Weekly Action Tip #205: What you focus on expands!" },
  { id: "FTwYZnYdBXY", title: "Harnessing the Power of Data and Real Estate Reviews" },
  { id: "AJUi7N3aKpY", title: "Setting Your Sights on a Shared Vision" },
  { id: "ROAQok5inj0", title: "Weekly Action Tip #204: Start your 4th quarter off right" },
  { id: "-bhWXNzqhHc", title: "Getting Ready for the Rollercoaster" },
  { id: "GuQkRscKxjE", title: "Support, Camaraderie, and Lessons Learned at the Ninja Selling Guide Camp" },
  { id: "aaBCsm2ri8g", title: "Weekly Action Tip #203: Getting rid of old ways" },
  { id: "jq3Gj94fh0U", title: "Practicing Effective Internal Communication" },
  { id: "t5nB_AOmv-0", title: "The Power of a Clear Database" },
  { id: "hHFobAnxcQw", title: "Weekly Action Tip #202: Seek meaningful interaction" },
  { id: "gHpq6Ablb4Q", title: "Waving the Company Flag" },
  { id: "XQ96ztH_9ac", title: "The Dangers in Dating Your Interest Rate" },
  { id: "7o8LbFcGnOQ", title: "Weekly Action Tip #201: Time to be the proactive trusted advisor" },
  { id: "Q1RFyRMs2L4", title: "Going 'Off the Leash'" },
  { id: "dlbRtc7AYEQ", title: "Winning the Day with Agendas and the Ninja Nine" },
  { id: "DYP43CyU3e4", title: "Weekly Action Tip #200: Back to the basics" },
  { id: "J3618LQ8wk0", title: "Abundance Vs. Scarcity Mindset" },
  { id: "ZMwUiUZtFVI", title: "Postcards: Doing Them the Right Way" },
  { id: "_vtFOEKQa3U", title: "Weekly Action Tip #199: Amp the FLOW" },
  { id: "UKnMj9Hf8xo", title: "Have-To vs Get-To" },
  { id: "u5YVRqJBRKg", title: "Navigating False Flats to Keep Your Business Booming" },
  { id: "5UThbXfwQoA", title: "Weekly Action Tip #198: What do I send?" },
  { id: "CRWe1eirLYU", title: "The Perception of Power, Party, Peace, and Perfection Personality Profiles Personified and Placated" },
  { id: "FGlj1Okm6Gk", title: "Perfecting Real Estate Reviews for Today's Marketplace" },
  { id: "IflUfddIgNM", title: "Weekly Action Tip #196: Mindset, Skillset, Actions" },
  { id: "wITbrOHEWAg", title: "The Power of Creating Raving Fans" },
  { id: "94L8zwj82g4", title: "Never Stop Building Your Skill Set" },
  { id: "9EWeSocu09c", title: "Weekly Action Tip #196: 3 Circles of Life" },
  { id: "Wo4NXpO17Ok", title: "Navigating a Reactionary Society" },
  { id: "3l8jPWWKvBI", title: "Launching Listings—The Return" },
  { id: "fOMLGwibbuc", title: "Weekly Action Tip #195: Crack the Code on Your Datatbase" },
  { id: "Lv6EsNCr8_w", title: "Serving Up Success" },
  { id: "me6shlzYhb8", title: "Relationships, Service, and Building Social Proof" },
  { id: "NlCDzEa_qr8", title: "Weekly Action Tip #194: Why do we procrastinate?" },
  { id: "9-sZ9NQW7_M", title: "Let's Talk Pricing Sensitivity!" },
  { id: "iLcIS_VmoG0", title: "Networking The Right Way" },
  { id: "0xgmGSW7WEo", title: "Weekly Action Tip #193: Is now a good time to buy?" },
  { id: "2AR7iv-SlXQ", title: "Becoming a Track Star in the Real Estate Field" },
  { id: "z01fXSZuEDI", title: "Bringing Clarity to Price Drops" },
  { id: "s4h4KZeZst4", title: "Navigating the Current Market Scooch" },
  { id: "sJk9apcIfEo", title: "Call it a \"Shimmy\"" },
  { id: "8YxCBDQCaeo", title: "Weekly Action Tip #191: Winning an offer without bidding the highest price" },
  { id: "I1t3DK9zEII", title: "You're Not Losing Buyers!" },
  { id: "JI_hP4u-A00", title: "Permission Granted" },
  { id: "7NFhCPEk__I", title: "Weekly Action Tip #190: Making the complex simple" },
  { id: "8UCucqSdfKg", title: "What If?" },
  { id: "Bi2VNcDT7gw", title: "Is Time on Your Side?" },
  { id: "CtDxXhOB7E4", title: "Weekly Action Tip #189: Burnout and Ask a Ninja!" },
  { id: "jMqo0kTvMjc", title: "Walking the Ninja Selling Path with Larry Kendall - Part 2" },
  { id: "YFfeZ6irpxw", title: "Walking the Ninja Selling Path with Larry Kendall - Part 1" },
  { id: "c16wsJZjPeE", title: "Weekly Action Tip #188: Why use the 10 step buyer process?" },
  { id: "gSoSg1S-wQ4", title: "Be Careful What You Call an Investment" },
  { id: "CaTFlUFMp0I", title: "Setting Sellers' Expectations" },
  { id: "ywBblPVIpaQ", title: "Weekly Action Tip #187: Do you have faith?" },
  { id: "YdyYkYOSiYA", title: "Focusing on Abundance and Opportunity" },
  { id: "Rdmu49y-hLg", title: "Ninja Selling Beyond the Real Estate World with McKennan Hansen" },
  { id: "9pPMba3MX0k", title: "Weekly Action Tip #186: Lets quit what's working" },
  { id: "sTlLCbdIefc", title: "Situational Relationships" },
  { id: "yUW96eAZBmM", title: "Back Into the Wild" },
  { id: "zSOhoUGoODw", title: "Make This Your Gap Year" },
  { id: "sgIPqiVABII", title: "Weekly Action Tip #185: Lets show some caring" },
  { id: "dRqqX4QvEO8", title: "What You Focus on Expands" },
  { id: "lHI3tgB866o", title: "Weekly Action Tip #184: 5 questions to ask your buyers" },
  { id: "p15YL4syGZI", title: "Weekly Action Tip #183: Be the source of information" },
  { id: "0rJTBitYQ3Y", title: "Action Tip #182: Rating Hot & Warm List" },
  { id: "8cnG45MMH2E", title: "Action Tip #181: Are you going to be a player or a victim?" },
  { id: "apC97ejyWdo", title: "Action Tip #180: The Power of Auto-FLOW" },
  { id: "Od-_MP-Xhpw", title: "Action Tip #179: I have to get better" },
  { id: "Q3Lq0FWGJaA", title: "Action Tip #178: When Buyer's Regret Their Decision" },
  { id: "U0_aeGVXNJs", title: "Action Tip #177: The Zip Lock Bag" },
  { id: "nmm28QKgaHM", title: "Action Tip #176: Why Do Ninjas Exist?" },
  { id: "IZfsmHPm7W4", title: "Action Tip #175: The Dinner Playhouse Story" },
  { id: "ejC4rzQYoWA", title: "Action Tip #174: The Conversation is the Relationship" },
  { id: "7Q1hqszLJ4M", title: "Action Tip #173: Use this trick when making a phone call" },
  { id: "xWIZGL5Bib8", title: "Action Tip #172: How to get off the \"treadmill\"" },
  { id: "PcyEV1ZKeho", title: "Action Tip #171: Focus on this Skillset" },
  { id: "2bfFs1n5kZ0", title: "Action Tip #170: 10 Step Formula to a Successful 2022" },
  { id: "FGOcbj_n-EU", title: "Best of Weekly Action Tips #8: Excellence is a Habit" },
  { id: "BzJVYKK9uW8", title: "Best of Weekly Action Tips #7: Power of Process" },
  { id: "xgIC066Yk0s", title: "Best of Weekly Action Tips #6: Daruma Doll" },
  { id: "faN5E1m5Ajs", title: "Best of Weekly Action Tips #5: Word of the Year" },
  { id: "8b-KmXHYijA", title: "Best of Weekly Action Tips #4: Solve for Price" },
  { id: "_pTKAFHUvl0", title: "Best of Weekly Action Tips #3: Blue Footed Booby" },
  { id: "_9s1laeiYGo", title: "Best of Weekly Action Tips #2: Best Lead Generation Activity" },
  { id: "fHjA3deWjS4", title: "Best of Weekly Action Tips #1: Never Break the Chain" },
  { id: "gCDBVbwsQ5g", title: "Action Tip #169: What is your Identity?" },
  { id: "heZ3S__Gjwg", title: "Action Tip #168: It's Business Planning Season!" },
  { id: "OFEWuUtFDBQ", title: "Action Tip #167: \"Adding\" to our Business" },
  { id: "ja8Iu1xc2_4", title: "Action Tip #148: Why follow a process?" },
  { id: "jihcOzq_nbg", title: "Action Tip#147: Being Grateful" },
  { id: "Z8iukrEDVLg", title: "Action Tip #146: Fun Facts" },
  { id: "QPda-gDmUOg", title: "Action Tip #145: The Hour of Power" },
  { id: "dELj50aW0Gg", title: "Action Tip #144: How are you time blocking?" },
  { id: "tpCSDUsbTsY", title: "Action Tip #142: How do we help our people?" },
  { id: "ZUPmI4w3G7E", title: "Be the source of information" },
  { id: "UATu-BrYbu4", title: "How to stay on top of your Ninja Nine" },
  { id: "0El6GlgTG_4", title: "Action Tip #139: Why do customer service calls?" },
  { id: "A2kYkFUAYd0", title: "What is your resistance" },
  { id: "tdm5JXXEjzU", title: "What is your Ninja competence level?" },
  { id: "8C5B5JjXcn4", title: "Will your listing make the cut?" },
  { id: "SdsscMPiShI", title: "Solve for Price" },
  { id: "ohOsUUZhIcY", title: "Ninja Morning Routine" },
  { id: "Mau3dti1c20", title: "What do you really want?" },
  { id: "9zmn7PbS6Zc", title: "Action Tip #118 - The Power of Process" },
  { id: "35F5xj3DaiU", title: "Action Tip #117 - It's Business Planning Month" },
  { id: "C5DRuM0xV8U", title: "Action Tip #116 - Your 50 Live Interviews" },
  { id: "HtLnbYcSsA0", title: "Number 5 in the 5 rules of Ninja selling is: Don't get attached to the outcome" },
  { id: "MOZ4YY-rxGU", title: "Gratitudes" },
  { id: "HXf2015FQF8", title: "Number 3 in the 5 rules of Ninja selling is: Do what you say and keep your commitments." },
  { id: "Nhu2NRNc7_k", title: "Finding a new comfort level" },
  { id: "QoxskHww5kE", title: "Physical distancing not social" },
  { id: "U3PG70KesA4", title: "DO YOUR HOT LIST" },
  { id: "hnU70mOV6Wk", title: "3 tips heading into fall" },
  { id: "DNrXT_k3Wvk", title: "Success Habit #6" },
  { id: "uWr7HMdqaos", title: "Success Habit #3" },
  { id: "mBjsEmhoURI", title: "Do you have a process?" },
  { id: "HjiypH-WT7I", title: "Scorecards" },
  { id: "87o9VOAnzeg", title: "Non-negotiables" },
  { id: "w5bGhLe5shI", title: "The Realtor's Prayer Episode #110" },
  { id: "0ZdiUYcAlI0", title: "How's Your Accountability? Episode #109" },
  { id: "c14lpPWXhGo", title: "The Infinite Game. Episode #108" },
  { id: "ZTjelvpR_Nc", title: "This is a set up! Episode #107" },
  { id: "AZ_73Sq-fJ8", title: "What is Ninja Selling" },
  { id: "rg0Sj2IETn4", title: "Atomic Habits. Episode #106" },
  { id: "Oab0zgY2QQ8", title: "Ninja Selling Testimonials" },
  { id: "docUDABvL5U", title: "Welcome to the Ninja Path" },
  { id: "S3nw15VL1Hs", title: "Bring Your A Game. Episode #104" },
  { id: "FVrYupJdnEE", title: "Ninja Weekly Routine Part 3" },
  { id: "ecAJiCnEGNk", title: "Ninja Weekly Routine Part 2, continued from March 6!" },
  { id: "y0gfGCl8-zQ", title: "Ninja Selling Results" },
  { id: "LPbaGoudkuU", title: "Exciting News!" },
  { id: "mdLUduzu-xU", title: "Give Yourself a Grade" },
  { id: "aExFl5hYEP0", title: "Am I enough" },
  { id: "Z9oemKxPkZI", title: "Fix your phone and a real estate update" },
  { id: "wUi7d0PlYgU", title: "The One Thing" },
  { id: "SQplLwWwh7k", title: "All of our people are wondering what is going on with the values in their neighborhood!" },
  { id: "bkOPc6FqecY", title: "The question they are all asking." },
  { id: "eyt9klIATyM", title: "Larry Kendall's COVID-19 Response" },
  { id: "mKAFCtXgfZA", title: "Plant seeds now!" },
  { id: "GjxTaOTgbVw", title: "More Ninjas Ideas around COVID-19." },
  { id: "rbrx14Qoz7Y", title: "Let's stay valuable as Ninjas!" },
  { id: "zr2wR0vWxNA", title: "Ninjas and COVID-19" },
  { id: "nWYXgyrNupE", title: "Ninja Weekly Routine Broken Down by Don Tennessen" },
  { id: "0bIpMArb9dc", title: "I haven't talked to them in 2 years!" },
  { id: "kgcCTVvD-c8", title: "Revisit your \"Word of the Year\"" },
  { id: "Piz0uLcTs2I", title: "Do you remember a key to increasing your income per hour?" },
  { id: "dUboaB3E7TU", title: "Every day we have a choice of how we \"show up\"." },
  { id: "u2UoJvra0Us", title: "Simon Sinek says...Start with Why" },
  { id: "YTgF67FCo5E", title: "Your \"One Day\"" },
  { id: "Ypt6UiaRyA4", title: "New Year Habits and how they influence your year as a Ninja." },
  { id: "C0kmujH9uUg", title: "Create a Real Estate Review" },
  { id: "0yQI3bcSrBo", title: "The best lead generation activity ever!" },
  { id: "ge6ZluujyzI", title: "The steps in MLS to prepare a RER" },
  { id: "v105U9YzpMA", title: "Real Estate Reviews Revisited." },
  { id: "l5ntvymCYZ4", title: "The start of a fantastic 2020!" },
  { id: "OLNxKfZhqlA", title: "This is the last Ninja Nation Action tip for 2019!" },
  { id: "7dBLbAGQNKE", title: "Word of the year" },
  { id: "sEBAdnYPY2E", title: "It's Monday the 23rd of December!!!" },
  { id: "7gCTXF460ws", title: "Work Life Harmony is the goal" },
  { id: "La7gKNmdCbY", title: "This is a great way to stay on your Ninja Path during the Holidays." },
  { id: "rd7Fwa2FLjI", title: "Use the Five Magic Questions this Holiday Season!" },
  { id: "i88Zqii-dqU", title: "What a great way to end your year!" },
  { id: "GtCcrT8AqYg", title: "Happy Thanksgiving from all of us at Ninja Selling" },
  { id: "Wwi42Dr1q9A", title: "What is the Real Reason for a Business Plan?" },
  { id: "SGVADG05G5k", title: "Week 1 post Installation" },
  { id: "n-r1yxw4qPM", title: "Do your Pre Flight Checklist" },
  { id: "KHBhJU02Boc", title: "Ninja Business Planning week 3" },
  { id: "EjU4yMVhlu8", title: "Get clear on what your Financial Goal for 2020, the Ninja Way." },
  { id: "gAP30uJrZWw", title: "Life List creation" },
  { id: "py6pKEst_Hc", title: "Ninja Business Plan Step One.  Build your Life List...your \"Why\"." },
  { id: "gcR4KkChDlU", title: "For Ninjas creating Fabled Service is everything." },
  { id: "640TpBq_seA", title: "How distractions keep us from making decisions" },
  { id: "Wr6SfcxYftA", title: "In a slump?" }
]

export const ninjaConcepts: NinjaConcept[] = [
  {
    id: "four-cornerstones",
    name: "The Four Cornerstones",
    description: "The four pillars that form the philosophical and practical foundation of the entire Ninja Selling system.",
    deepDive: "Larry Kendall built Ninja Selling on four cornerstones that work together as a complete system. Cornerstone 1, Personal Mastery, means working on yourself before you work on your business — your mindset, energy, habits, and personal growth determine the ceiling of your results. Cornerstone 2, Stop Selling Start Solving, flips the traditional sales model: instead of persuading people to buy, you listen deeply and help them solve real problems. This creates trust and eliminates the adversarial dynamic of traditional selling. Cornerstone 3, Ninja Business Strategy, provides the tactical framework — a referral-based business model powered by your database, relationships, and consistent daily habits (the Ninja Nine). Cornerstone 4, Connect & Communicate, recognizes that real estate is a relationship business. Authentic human connection — not marketing funnels or cold outreach — is what produces lasting, compounding results. When all four cornerstones are in place, your business grows organically because people genuinely want to work with you and refer you.",
    principles: [
      "Personal Mastery: Your business can only grow as fast as you do — invest in mindset, emotional intelligence, physical health, and continuous learning before tactics",
      "Stop Selling, Start Solving: The best 'sales technique' is genuine curiosity about people's problems and a commitment to helping them find solutions, even if it doesn't result in a transaction for you",
      "Ninja Business Strategy: Build a referral-based business powered by relationships and consistent daily habits rather than expensive lead generation — your database is your greatest asset",
      "Connect & Communicate: Master the art of authentic conversation through active listening, empathy, and the FORD method — people do business with those who genuinely care about them"
    ],
    actionItems: [
      "Start each day with a morning routine: gratitude, affirmations, visualization, and goal review (this IS Personal Mastery in practice)",
      "In your next 5 conversations, replace 'How's the market?' with 'What's going on in your world? How can I help?'",
      "Write down your top 50 relationships and assess: when did I last have a meaningful conversation with each person?",
      "Create your annual business plan starting with your Life List — connect your financial goals to your personal 'why'"
    ]
  },
  {
    id: "ninja-nine",
    name: "The Ninja Nine",
    description: "Nine specific daily and weekly disciplines that, done consistently, create a compounding flywheel of relationships, referrals, and closings.",
    deepDive: "The Ninja Nine are the heartbeat of the system. They are divided into daily habits (1-5) and weekly habits (6-9). The magic is in the consistency — not perfection. Habit 1, Gratitude, rewires your brain to focus on abundance rather than scarcity. Habit 2, Affirmations & Visualization, programs your subconscious to pursue your goals. Habit 3, Review Goals & Schedule, ensures you work intentionally rather than reactively. Habit 4, Write 2 Personal Notes, creates tangible touchpoints that make people feel valued — handwritten notes have nearly a 100% open rate. Habit 5, Live Interviews (phone calls), is where the real business happens — aim for 50 live conversations per week. Habit 6, Track on the Ninja Scorecard, provides accountability and helps you see which inputs drive results. Habit 7, Ninja Meeting, gives you weekly accountability with peers. Habit 8, Prepare & Practice, means role-playing scripts and consultations so you're sharp when it counts. Habit 9, E-Time (Education), ensures you never stop growing. Most agents who commit to the Ninja Nine for 90 consecutive days see a measurable increase in closings within 6 months.",
    principles: [
      "1. Gratitude & Appreciation — Write 3 things you're grateful for each morning. This shifts your mindset from scarcity to abundance and changes the energy you bring to every interaction",
      "2. Affirmations & Visualization — Read your affirmations aloud and spend 5 minutes visualizing your goals as already achieved. Your subconscious mind doesn't distinguish between vivid imagination and reality",
      "3. Review Goals & Schedule — Before your day starts, review your annual goals, monthly targets, and today's schedule. Know your 'Big 3' priorities for the day",
      "4. Write 2 Personal Notes — Handwritten notes (not business cards, not emails) to people in your database. Reference something personal. This is the single highest-ROI activity in Ninja Selling",
      "5. Live Interviews — Make phone calls to your database. Not scripts. Real conversations. Ask about their lives using FORD. Aim for 10 live conversations per day / 50 per week",
      "6. Ninja Scorecard — Track your daily activities (notes sent, calls made, appointments set). What gets measured gets managed. Review weekly to identify patterns",
      "7. Weekly Ninja Meeting — Meet with your accountability group or team weekly to share wins, challenges, and commitments for the coming week",
      "8. Prepare & Practice — Role-play buyer consultations, seller presentations, pricing conversations, and objection handling. Skills degrade without practice",
      "9. E-Time (Education) — Dedicate 2+ hours per week to learning: read books, watch training videos, attend seminars, listen to podcasts. Growth is the foundation of everything"
    ],
    actionItems: [
      "Tomorrow morning: set your alarm 30 minutes earlier and do habits 1-3 before touching your phone",
      "Today: order 100 personal note cards and a book of stamps — have them at your desk by next week",
      "This week: block two 1-hour 'phone time' sessions on your calendar and make at least 20 live calls",
      "Print or create a Ninja Scorecard spreadsheet and start tracking daily: notes sent, calls made, appointments set, contracts written",
      "Find or form a Ninja accountability group — commit to a weekly 30-minute meeting"
    ]
  },
  {
    id: "ford-method",
    name: "FORD Method",
    description: "A conversation framework — Family, Occupation, Recreation, Dreams — that turns small talk into meaningful relationships and naturally surfaces real estate opportunities.",
    deepDive: "FORD is not a script — it's a mindset for genuine conversations. Most agents default to talking about real estate, which puts people on guard. FORD flips this: you talk about THEM, and real estate comes up naturally. Family questions build emotional rapport ('How are the kids adjusting to the new school?'). Occupation questions uncover financial changes and relocations ('I heard your company is expanding — are they moving offices?'). Recreation questions reveal lifestyle preferences that connect to housing ('You mentioned you're getting into gardening — are you running out of yard space?'). Dreams questions are the gold mine — this is where people tell you about their future, and their future almost always involves real estate ('We've always dreamed of living near the coast when the kids are grown'). The key discipline is logging FORD notes in your CRM after every conversation, so when you follow up weeks or months later, you can reference specific details. This makes people feel remembered and valued — which is why they refer you.",
    principles: [
      "Family: Ask about their spouse/partner, children, parents, pets, extended family. People light up when they talk about the people they love — and family changes (new baby, kids leaving for college, aging parents) often trigger real estate decisions",
      "Occupation: Understand what they do for work, how it's going, any changes ahead. Job changes, promotions, relocations, and retirements are among the top reasons people buy or sell",
      "Recreation: Learn what they do for fun — hobbies, sports, travel, volunteer work. This reveals lifestyle needs (bigger garage for the boat, closer to the trails, extra bedroom for the home gym) and gives you pop-by gift ideas",
      "Dreams: Ask 'If you could wave a magic wand, what would your life look like in 5 years?' Dreams reveal future real estate needs before the person even realizes they're needs. This is where the biggest opportunities live",
      "The 80/20 Rule: Listen 80% of the time, talk 20%. Ask follow-up questions. The person who asks the questions controls the conversation — and the person who listens earns the trust"
    ],
    actionItems: [
      "After your next 5 conversations, immediately open your CRM and log at least 2 FORD notes per person",
      "Before your next pop-by or call, review that person's FORD notes and reference something specific ('Last time we talked, you mentioned Sarah was starting soccer — how's that going?')",
      "Practice asking Dreams questions this week — it feels uncomfortable at first, but it's where the magic happens",
      "Create a pop-by gift list based on Recreation notes (e.g., a gardening book for the contact who loves their yard)",
      "Set a weekly reminder to review 10 contacts' FORD notes and identify who's due for a personal touch"
    ]
  },
  {
    id: "flow-system",
    name: "Flow & Auto-Flow",
    description: "A two-layered system for staying top-of-mind with your entire database — automated baseline touches plus intentional personal connections on a scheduled cadence.",
    deepDive: "Flow solves the biggest problem in relationship-based business: people forget about you. Even your biggest fans will call another agent if you haven't been in touch. The system has two layers. Auto-Flow is the baseline: automated monthly touches (email newsletters, market reports, community updates) that keep your name in front of your database with zero daily effort. You set it up once and it runs. Personal Flow is the layer that builds real loyalty: handwritten notes, phone calls, pop-bys (stopping by with a small gift), and Customer Service Calls. The cadence depends on the contact tier — your top 50 get monthly personal touches, your next 100 get quarterly, and everyone else gets Auto-Flow plus occasional personal contact. Customer Service Calls are a Ninja signature: calling past clients 30 days, 90 days, and annually after closing to ask 'How's the house? Is there anything I can help with?' This generates referrals at an astonishing rate because no other agent does this. The compounding effect is powerful — after 2-3 years of consistent Flow, most of your business comes inbound from people who already trust you.",
    principles: [
      "Auto-Flow: Set up automated monthly value-add content (market reports, home maintenance tips, local events) that provides genuine value — not self-promotional 'just listed/just sold' blasts",
      "Personal Flow: Schedule intentional personal touches — handwritten notes, phone calls, pop-bys, and face-to-face meetings — on a cadence that matches the relationship tier",
      "Customer Service Calls: Call every past client at 30 days, 90 days, and annually after closing. Ask 'How's the house? Anything I can help with?' This single habit generates more referrals than any marketing campaign",
      "Consistency beats intensity: 12 small monthly touches outperform 1 big annual event. People need to hear from you 7-12 times per year to remember you when a real estate need arises",
      "Tiered approach: A-contacts (top 50) get monthly personal Flow + Auto-Flow. B-contacts (next 100-150) get quarterly personal Flow + Auto-Flow. C-contacts get Auto-Flow only"
    ],
    actionItems: [
      "This week: set up a monthly Auto-Flow email using your CRM or a tool like Mailchimp — focus on market insights and community value, not self-promotion",
      "Create a spreadsheet of your top 50 contacts and schedule one personal touch per person per month (note, call, or pop-by)",
      "Pull a list of all past clients and schedule Customer Service Calls — start with anyone who closed in the last 12 months",
      "Plan your next quarter's pop-by theme (e.g., pumpkin pie at Thanksgiving, flower seeds in spring) and order supplies",
      "Build a 12-month Flow Calendar on one page: map out which Auto-Flow content and pop-by themes happen each month"
    ]
  },
  {
    id: "real-estate-reviews",
    name: "Real Estate Reviews",
    description: "Annual property value reviews that position you as a trusted financial advisor — not a salesperson — while naturally uncovering listing, buying, and referral opportunities.",
    deepDive: "The Annual Real Estate Review is one of the most powerful tools in the Ninja system because it provides massive value with zero sales pressure. Here's how it works: you contact homeowners in your database (past clients, neighbors, sphere) and offer a free annual review of their property's current market value, equity position, and neighborhood trends — similar to how a financial advisor reviews your portfolio. During the review, you walk them through a professional report showing what their home is worth today, how much equity they've built, whether their insurance coverage is adequate, and what's happening in their local market. You're not asking them to sell. You're giving them information they genuinely need. The magic is in the outcomes: during these conversations, people naturally tell you about their plans. 'Actually, we've been thinking about downsizing.' 'My neighbor mentioned they might sell.' 'My sister just got transferred and needs an agent in Denver.' You didn't ask for business — they volunteered it, because you provided real value and they trust you. Agents who do 5-10 reviews per week consistently report that it becomes their number one source of listings and referrals.",
    principles: [
      "Lead with value: Prepare a professional CMA-style report showing current home value, equity growth since purchase, and comparable sales — this is genuinely useful information homeowners want",
      "Review insurance coverage: Many homeowners are underinsured as their home value has increased. Flagging this shows you care about their financial well-being, not just transactions",
      "Discuss neighborhood trends: Share recent sales, days on market, and price trends in their specific neighborhood. Local expertise builds trust and authority",
      "Position as a recurring service: Frame this as something you do annually for all your clients, like a financial check-up. This creates an expectation of ongoing relationship",
      "Opportunities surface naturally: Don't pitch. When people trust you and you're asking about their lives (FORD), they'll tell you about their plans. 'Who else might find this valuable?' is the only 'ask' you need"
    ],
    actionItems: [
      "Create a professional Real Estate Review template (1-2 page report with property value, equity, neighborhood comps, and insurance reminder)",
      "Pull a list of all homeowners in your database and schedule 5 review offers per week via phone calls",
      "After each review, send a follow-up email with the report summary and a handwritten thank-you note",
      "Host a quarterly 'Market Update' event (in-person or virtual) for groups of 10-20 contacts as a scaled version of the review",
      "Track your reviews on your Ninja Scorecard: reviews offered, reviews completed, and opportunities generated"
    ]
  },
  {
    id: "buyer-seller-process",
    name: "The Ninja Buyer & Seller Process",
    description: "Structured, consultative processes for guiding buyers and sellers that replace high-pressure tactics with trust, education, and genuine problem-solving.",
    deepDive: "Traditional agents show houses and hope for the best. Ninjas follow a structured process that positions them as trusted consultants. For buyers, the 10-Step Buyer Process starts with a formal Buyer Consultation BEFORE showing any homes. In this meeting, you understand their needs, timeline, financial situation, and dreams (FORD). You educate them on the buying process, set expectations, and establish a working agreement. Only then do you show homes — and because you listened first, you show fewer homes that are better matches. For sellers, the process starts with a Pre-Listing Packet (sent before you meet) that educates them on your approach and the selling process. The Listing Consultation is where you present your market analysis and have the critical pricing conversation. Ninjas 'solve for price' — meaning you help sellers understand what the market will bear, rather than telling them what they want to hear. This requires courage, but it earns enormous trust and leads to properly priced listings that sell faster. The process doesn't end at closing: the post-closing follow-up (Customer Service Calls at 30, 90, and 365 days) transitions the client into your long-term database for future business and referrals.",
    principles: [
      "Buyer Consultation first, always: Never show homes without first understanding needs, timeline, finances, and motivations. This meeting establishes trust, sets expectations, and saves everyone time",
      "10-Step Buyer Process: (1) Lead generation → (2) Initial contact → (3) Buyer consultation → (4) Pre-approval → (5) Home search → (6) Showing homes → (7) Writing offers → (8) Under contract → (9) Closing → (10) Post-closing follow-up and referral cultivation",
      "Pre-Listing Packet: Send an educational packet before the listing appointment that demonstrates your value, explains your process, and sets you apart from agents who just 'show up and pitch'",
      "Solve for price: Have the courage to present honest market data and recommend the right price, even if it's lower than the seller hopes. Properly priced homes sell faster, net more, and generate referrals",
      "Post-closing is where the real business starts: The transaction is just the beginning of the relationship. Customer Service Calls at 30, 90, and 365 days generate more referrals than any marketing"
    ],
    actionItems: [
      "Create or refine your Buyer Consultation presentation — include your process overview, market education, and a working agreement for the buyer to sign",
      "Build a Pre-Listing Packet: include your bio, testimonials, marketing plan, pricing philosophy, and a brief overview of the Ninja selling process",
      "Role-play the pricing conversation with a partner this week: practice presenting comps and recommending a price with confidence and empathy",
      "Set up a post-closing system in your CRM: automated reminders for 30-day, 90-day, and annual Customer Service Calls for every closed client",
      "After your next closing, add the client to your top contacts list and send a handwritten note within 48 hours"
    ]
  },
  {
    id: "pie-time",
    name: "PIE Time Management",
    description: "A time-blocking framework that divides your week into Proactive, Income, and Education time — ensuring you build future business even when current business is busy.",
    deepDive: "Most agents spend almost all their time on I-Time (Income-producing activities like showings, negotiations, and closings) and wonder why their pipeline dries up between transactions. PIE solves this by making P-Time (Proactive) the priority. P-Time is when you build your future business: calling your database, writing notes, doing pop-bys, conducting Real Estate Reviews, and nurturing relationships. I-Time is when you service current business: showing homes, writing contracts, managing transactions. E-Time is when you grow: reading, attending training, watching Ninja Selling videos, role-playing with a partner. The Ninja ideal is a 20-hour productive work week — not because you work less, but because you work smarter. A typical Ninja week looks like: 10 hours of P-Time (mornings, before the world gets busy), 8 hours of I-Time (afternoons, when clients are available), and 2 hours of E-Time (one dedicated learning block per week). The critical discipline is protecting your P-Time. When business gets busy, the temptation is to skip P-Time and only do I-Time. But P-Time is what filled your pipeline in the first place — skipping it guarantees a future slowdown. Block your P-Time on your calendar like an unmovable appointment.",
    principles: [
      "P-Time (Proactive): The engine of your future business. Includes database calls, handwritten notes, pop-bys, Real Estate Reviews, and relationship building. Block this FIRST on your calendar, ideally in the morning",
      "I-Time (Income): Servicing current clients — showings, negotiations, inspections, closings. This is important but reactive. Without P-Time feeding the pipeline, I-Time eventually dries up",
      "E-Time (Education): Continuous learning — books, training videos, role-play, seminars, coaching. Allocate at least 2 hours per week. The best agents never stop learning",
      "The Ninja 20-Hour Week: Aim for ~10 hours P-Time, ~8 hours I-Time, ~2 hours E-Time. This isn't about working less — it's about eliminating low-value busywork and focusing on high-impact activities",
      "Protect P-Time fiercely: When you get busy with transactions, your instinct is to stop doing P-Time. This is exactly when you must NOT stop. Treat P-Time like a client appointment that cannot be rescheduled"
    ],
    actionItems: [
      "Open your calendar right now and block 2 hours of P-Time every weekday morning for the next 4 weeks — label them 'Ninja P-Time (DO NOT MOVE)'",
      "Block one 2-hour E-Time slot per week (e.g., Friday morning) for reading, watching training videos, or role-playing",
      "At the end of each week, log your actual PIE hours: How much time did you spend on P, I, and E? Most agents are shocked at how little P-Time they actually do",
      "During your next busy period, resist the urge to cancel P-Time — even 30 minutes of calls and notes is better than zero",
      "Share your PIE time goals with your accountability partner or Ninja group for weekly check-ins"
    ]
  },
  {
    id: "handwritten-notes",
    name: "Handwritten Notes & Personal Touches",
    description: "The highest-ROI habit in real estate: handwritten notes have a near-100% open rate and make people feel genuinely valued in a world of digital noise.",
    deepDive: "In an era of email blasts and social media ads, a handwritten note is almost shockingly personal. It takes 2 minutes to write, costs less than a dollar to send, and creates an emotional impact that no digital communication can match. The Ninja system calls for 2 personal notes per day — that's 10 per week, roughly 500 per year. Over time, this single habit seeds your database with goodwill that converts to referrals. The key word is 'personal.' These are NOT 'just sold' postcards or business announcements. They're notes that reference something specific about the person: 'Great seeing you at the farmers market last Saturday — Emma is getting so tall!' or 'Congratulations on the new role at work. You've been working so hard for this.' When someone receives a note like that, they don't throw it away — they put it on their fridge. And when their coworker mentions wanting to buy a house, guess whose name comes to mind? Pop-bys work on the same principle: showing up at someone's door with a small, thoughtful gift (cookies at the holidays, flower seeds in spring, pumpkin pie at Thanksgiving) creates a face-to-face moment that deepens the relationship. The combination of handwritten notes, pop-bys, and phone calls is what makes Personal Flow so powerful.",
    principles: [
      "Write 2 personal notes per day, every business day — this is Ninja Nine habit #4 and the single most impactful activity in your Ninja practice. 500 notes per year creates an enormous trust bank",
      "Keep it personal, not promotional: Reference specific details from FORD conversations. Never include business cards, listings, or calls to action. The note IS the marketing — because it shows you care",
      "Handwritten notes have a near-100% open rate: Every piece of handwritten mail gets opened. Compare that to email (~20% open rate) or social media (algorithm-dependent). This is the most direct line to someone's attention",
      "Pop-bys amplify the effect: Stopping by with a small, thoughtful gift creates a face-to-face moment. Keep gifts simple and seasonal ($5-10 max). The visit is the gift — the item is just the excuse",
      "Celebrate milestones generously: Birthdays, work anniversaries, kids' graduations, new pets, home purchase anniversaries. Your CRM + FORD notes make this easy — and people remember who remembered"
    ],
    actionItems: [
      "Order 200 quality, non-branded note cards and 2 books of stamps this week — have them on your desk where you can see them",
      "Set a daily alarm or calendar block for note-writing time (many Ninjas do it right after their morning routine)",
      "After every meaningful conversation this week, jot the person's name on a sticky note — they get a handwritten note within 48 hours",
      "Plan your next seasonal pop-by: choose a theme, order supplies for your top 25 contacts, and schedule delivery dates on your calendar",
      "Start a 'Notes Sent' tracker: tally marks on a whiteboard, a column on your Ninja Scorecard, or a simple spreadsheet. Aim for 10 per week minimum"
    ]
  }
]
